import { useCallback, useEffect, useState } from "react";
import { Link } from "react-router-dom";
import { effectiveBinderItems, finishLabel, binderItemsMatch } from "@gatcg/shared";
import CardArtTile from "../../components/CardArtTile";
import DisclosureChevron from "../../components/DisclosureChevron";
import type { Card, CollectionCardTracking, AccountUser, BinderItem, BinderSettings, CollectionEntry, PublicBinder, Trade, TradeStatus } from "@gatcg/shared";
import { accountApi } from "../../lib/accountApi";
import { useCardCatalog } from "../cards/useCardCatalog";
import Panel from "../../components/ui/Panel";
import Button from "../../components/ui/Button";

import BinderItemEditor from "./BinderItemEditor";
import Tabs, { TabPanel } from "../../components/ui/Tabs";
import DialogSheet from "../../components/ui/DialogSheet";
import CardResult from "../../components/CardResult";

const EMPTY_SETTINGS: BinderSettings = { public: false, tradeMethod: "either", location: "", notes: "", updatedAt: null };

function ItemRow({ cards, item, onDelete, onEdit }: { cards: Card[]; item: BinderItem; onDelete?: () => void; onEdit?: () => void }) {
  return <CardResult card={cards.find(card => card.uuid === item.cardUuid)} name={item.cardName} editionUuid={item.editionUuid ?? undefined}>
    <p className="text-xs text-ctp-subtext1">{item.setPrefix ? `${item.setPrefix} #${item.collectorNumber ?? "?"}` : "Unspecified printing"} · {item.kind === "wanted" && (!item.finish || item.finish === "unspecified") ? "Any finish" : finishLabel(item.finish)} · {item.condition} · {item.language}</p>
    <p className="mt-2 text-sm">{Math.max(0, item.quantity - item.reservedQuantity)} {item.kind === "wanted" ? "wanted" : "available"}{item.reservedQuantity ? ` · ${item.reservedQuantity} reserved` : ""}</p>
    {onEdit && <Button className="mt-2 w-full" variant="secondary" onClick={onEdit}>Edit listing</Button>}
    {onDelete && <Button className="mt-2 w-full" variant="secondary" onClick={onDelete}>Remove</Button>}
  </CardResult>;
}

function TradeCard({ trade, me, refresh, cards }: { cards: Card[]; trade: Trade; me: AccountUser; refresh: () => Promise<void> }) {
  const [busy, setBusy] = useState(false), [notice, setNotice] = useState<string | null>(null);
  const mine = trade.sender.profileSlug === me.profileSlug;
  const partner = mine ? trade.recipient : trade.sender;
  const act = async (status: TradeStatus | "sent" | "received") => { setBusy(true); setNotice(null); try { await accountApi.updateTradeStatus(trade.id, status); await refresh(); } catch (error) { setNotice(error instanceof Error ? error.message : "Trade could not be updated"); } finally { setBusy(false); } };
  const [counterOpen, setCounterOpen] = useState(false);
  const [counterMessage, setCounterMessage] = useState(trade.currentRevision.message);
  const [counterLines, setCounterLines] = useState(trade.currentRevision.lines);
  const counter = async () => { setBusy(true); setNotice(null); try { await accountApi.counterTrade(trade.id, counterLines.filter(line => line.quantity > 0), counterMessage); setCounterOpen(false); await refresh(); } catch (error) { setNotice(error instanceof Error ? error.message : "Counteroffer could not be sent"); } finally { setBusy(false); } };

  const open = ["sent", "countered"].includes(trade.status), active = ["accepted", "sender_sent", "recipient_sent", "both_sent"].includes(trade.status);
  return <Panel padding="sm"><div className="flex flex-wrap items-start justify-between gap-2"><div><p className="font-semibold">Trade with <Link to={`/users/${partner.profileSlug}`} className="text-ctp-blue hover:underline">{partner.displayName}</Link></p><p className="mt-1 text-xs uppercase tracking-wide text-ctp-yellow">{trade.status.replaceAll("_", " ")}</p></div><span className="text-xs text-ctp-subtext0">{new Date(trade.updatedAt).toLocaleDateString()}</span></div>
    <div className="mt-3 grid gap-2 sm:grid-cols-2">{(["sender_gives", "recipient_gives"] as const).map((direction) => <div key={direction} className="rounded-lg bg-ctp-surface0 p-3"><p className="text-xs font-semibold text-ctp-subtext1">{direction === "sender_gives" ? `${trade.sender.displayName} gives` : `${trade.recipient.displayName} gives`}</p>{trade.currentRevision.lines.filter((line) => line.direction === direction).map((line) => <div key={line.binderItemId} className="mt-2 flex items-center gap-2"><div className="w-16 shrink-0"><CardArtTile card={cards.find(card=>card.uuid===line.cardUuid)} name={line.cardName}/></div><p className="text-sm">{line.quantity}× {line.cardName} · {finishLabel(line.finish)}</p></div>)}</div>)}</div>
    {trade.currentRevision.message && <p className="mt-3 text-sm text-ctp-subtext1">“{trade.currentRevision.message}”</p>}
    {counterOpen && <DialogSheet title="Counteroffer" onDismiss={() => setCounterOpen(false)} dirty={counterMessage !== trade.currentRevision.message || JSON.stringify(counterLines) !== JSON.stringify(trade.currentRevision.lines)} dismissible={!busy} footer={<>{notice && <p role="alert">{notice}</p>}<Button disabled={busy || !counterLines.some(line => line.quantity > 0) || counterLines.some(line => !Number.isInteger(line.quantity) || line.quantity < 0 || line.quantity > 999)} onClick={() => void counter()}>Send counteroffer</Button></>}>
      {counterLines.map((line, index) => <div key={line.binderItemId} className="mb-3"><CardResult compactOnMobile card={cards.find(card => card.uuid === line.cardUuid)} name={line.cardName} editionUuid={line.editionUuid ?? undefined} newTab><p className="text-sm">{finishLabel(line.finish)}</p><label className="block text-sm">{line.direction === "sender_gives" ? trade.sender.displayName : trade.recipient.displayName} gives<input disabled={busy} aria-label={`Counter quantity for ${line.cardName}`} type="number" min={0} max={999} value={line.quantity} onChange={event => setCounterLines(rows => rows.map((row, i) => i === index ? { ...row, quantity: Number(event.target.value) } : row))} className="mt-1 min-h-12 w-full rounded-lg border border-ctp-surface1 bg-ctp-base px-3" /></label></CardResult></div>)}
      <label className="block text-sm">Message<textarea disabled={busy} value={counterMessage} onChange={event => setCounterMessage(event.target.value)} className="mt-1 min-h-24 w-full rounded-lg border border-ctp-surface1 bg-ctp-base p-3" /></label>
    </DialogSheet>}
    <div className="mt-3 flex flex-wrap gap-2">{open && <><Button disabled={busy} onClick={() => void act("accepted")}>Accept</Button><Button variant="secondary" disabled={busy} onClick={() => { setCounterLines(trade.currentRevision.lines); setCounterMessage(trade.currentRevision.message); setCounterOpen(true); }}>Counter</Button><Button variant="secondary" disabled={busy} onClick={() => void act("declined")}>Decline</Button>{mine && <Button variant="secondary" disabled={busy} onClick={() => void act("cancelled")}>Cancel</Button>}</>}{active && trade.status !== "both_sent" && <Button disabled={busy} onClick={() => void act("sent")}>Mark my cards sent</Button>}{trade.status === "both_sent" && <Button disabled={busy} onClick={() => void act("received")}>Confirm received</Button>}{active && <Button variant="secondary" disabled={busy} onClick={() => void act("disputed")}>Report a problem</Button>}</div>{notice && <p className="mt-2 text-xs text-ctp-yellow">{notice}</p>}
  </Panel>;
}

export default function TradingBinder({ publicSlug }: { publicSlug?: string } = {}) {
  const cards = useCardCatalog();
  const [user, setUser] = useState<AccountUser | null>();
  const [loadError, setLoadError] = useState<string | null>(null);
  const [loading, setLoading] = useState(true);
  const [tracking,setTracking]=useState<CollectionCardTracking[]>([]);
  const [settings, setSettings] = useState(EMPTY_SETTINGS), [items, setItems] = useState<BinderItem[]>([]), [collection, setCollection] = useState<CollectionEntry[]>([]);
  const [matches, setMatches] = useState<PublicBinder[]>([]), [trades, setTrades] = useState<Trade[]>([]), [tab, setTab] = useState<"binder" | "matches" | "offers">("binder");
  const [editor, setEditor] = useState<BinderItem | "new" | null>(null);
  const [filter, setNameFilter] = useState(""), [setFilter, setSetFilter] = useState("");
  const [matchLoading, setMatchLoading] = useState(false), [matchError, setMatchError] = useState("");
  const [partner, setPartner] = useState<PublicBinder | null>(null), [selected, setSelected] = useState<Record<string, number>>({}), [message, setMessage] = useState("");
  const loadMatches = async () => { setMatchLoading(true); setMatchError(""); try { setMatches((await accountApi.binderMatches()).binders); } catch (error) { setMatchError(error instanceof Error ? error.message : "Could not load matches."); } finally { setMatchLoading(false); } };

  const [publicView, setPublicView] = useState<PublicBinder | null>();
  const [busy, setBusy] = useState(false), [notice, setNotice] = useState<string | null>(null);
  const refresh = useCallback(async () => { const [binder, tradeResult, inventory, locations] = await Promise.all([accountApi.binder(), accountApi.trades(), accountApi.collection(), accountApi.collectionTracking()]);setCollection(inventory.entries);setTracking(locations.cards); setSettings(binder.settings); setItems(binder.items); setTrades(tradeResult.trades); }, []);
  useEffect(() => { if (publicSlug) { void accountApi.publicBinder(publicSlug).then(({ binder }) => setPublicView(binder)).catch(() => setPublicView(null)); return; } void accountApi.session().then(async ({ user: result }) => { setUser(result); if (result) { await refresh(); } }).catch(error => setLoadError(error instanceof Error ? error.message : "Could not load your binder.")).finally(() => setLoading(false)); }, [refresh, publicSlug]);
  const act = async (action: () => Promise<unknown>, success: string) => { setBusy(true); setNotice(null); try { await action(); setNotice(success); try { await refresh(); } catch { setNotice(`${success} Refresh failed. Reload to see the latest changes.`); } return true; } catch (error) { setNotice(error instanceof Error ? error.message : "Action failed"); return false; } finally { setBusy(false); } };
  if (publicSlug) return publicView === undefined ? <Panel className="mt-6">Loading binder…</Panel> : publicView ? <section className="mt-6"><Panel padding="sm"><h2 className="text-lg font-semibold">{publicView.owner.displayName}’s binder</h2><p className="mt-1 text-sm text-ctp-subtext1">{publicView.settings.tradeMethod} · {publicView.settings.location || "Location not listed"}</p>{publicView.settings.notes && <p className="mt-3 text-sm">{publicView.settings.notes}</p>}</Panel>{(["available", "wanted"] as const).map((group) => <div key={group} className="mt-6"><h2 className="text-lg font-semibold capitalize">{group}</h2><div className="mt-3 grid grid-cols-2 gap-3 sm:grid-cols-3 lg:grid-cols-4">{publicView.items.filter((item) => item.kind === group).map((item) => <ItemRow cards={cards} key={item.id} item={item} />)}</div></div>)}</section> : <Panel className="mt-6">This binder is private or unavailable.</Panel>;
  if (loadError) return <Panel className="mt-6"><p role="alert">{loadError}</p><Button className="mt-3" disabled={loading} onClick={() => { setLoading(true); void accountApi.session().then(async ({user: result}) => { setUser(result); if(result) await refresh(); setLoadError(null); }).catch(error => setLoadError(error instanceof Error ? error.message : "Could not load your binder.")).finally(() => setLoading(false)); }}>Retry</Button></Panel>;
  if (loading || user === undefined) return <Panel className="mt-6">Loading your trading binder…</Panel>;
  if (!user) return <Panel className="mt-6"><h2 className="text-lg font-semibold">Trading binder</h2><p className="mt-2 text-sm text-ctp-subtext1">Sign in to publish cards, find reciprocal matches, and make auditable trade offers.</p><Link to="/account" className="mt-4 inline-flex min-h-12 items-center rounded-lg bg-ctp-blue px-4 text-sm font-semibold text-ctp-base">Sign in</Link></Panel>;
  const visibleItems = effectiveBinderItems(collection,tracking,items);
  const ownAvailable = visibleItems.filter((item) => item.kind === "available" && item.quantity > item.reservedQuantity);
  const offerItems = partner ? [...ownAvailable, ...partner.items.filter((item) => item.kind === "available" && item.quantity > item.reservedQuantity)] : [];
  return <section className="mt-6">
    <Tabs baseId="trading" variant="pill" wrap label="Trading binder" active={tab} tabs={[{ key: "binder", label: "My Binder" }, { key: "matches", label: "Matches" }, { key: "offers", label: `Offers (${trades.length})` }]} onChange={value => { setTab(value); if (value === "matches") void loadMatches(); }} />
    {editor && <BinderItemEditor cards={cards} collection={collection} item={editor === "new" ? undefined : editor} onDismiss={() => setEditor(null)} onSaved={() => { setNotice("Listing saved."); void refresh().catch(() => setNotice("Listing saved. Refresh failed; reload to see it.")); }} />}
    {notice && <p role="status" className="mt-3 rounded-lg bg-ctp-surface0 p-3 text-sm text-ctp-yellow">{notice}</p>}
    <TabPanel baseId="trading" tab="binder" active={tab} className="mt-5 space-y-5"><Button onClick={() => setEditor("new")}>Add card</Button><Link to="/collection" className="ml-2 inline-flex min-h-12 items-center rounded-lg border border-ctp-surface1 px-4 text-sm">Select cards from collection</Link><p className="text-sm text-ctp-subtext1">Available quantities exclude cards in decks, loans, and accepted trades. Listing does not reserve physical copies.</p><details><summary className="flex min-h-12 cursor-pointer items-center gap-2 text-sm">Visibility and trading<DisclosureChevron/></summary><Panel><label className="mt-3 flex items-start gap-3 text-sm"><input type="checkbox" checked={settings.public} onChange={(event) => setSettings({ ...settings, public: event.target.checked })} className="mt-1 h-5 w-5" /><span><span className="font-medium">Publish my binder</span><br /><span className="text-ctp-subtext0">Only your binder listings and wants are public. Your collection and loans stay private.</span></span></label><div className="mt-4 grid gap-3 sm:grid-cols-2"><label className="text-xs text-ctp-subtext1">Trade method<select value={settings.tradeMethod} onChange={(event) => setSettings({ ...settings, tradeMethod: event.target.value as BinderSettings["tradeMethod"] })} className="mt-1 block min-h-12 w-full rounded-lg border border-ctp-surface1 bg-ctp-base px-3"><option value="either">Local or shipping</option><option value="local">Local only</option><option value="shipping">Shipping only</option></select></label><label className="text-xs text-ctp-subtext1">General location<input value={settings.location} onChange={(event) => setSettings({ ...settings, location: event.target.value })} placeholder="City, region, or country" className="mt-1 block min-h-12 w-full rounded-lg border border-ctp-surface1 bg-ctp-base px-3" /></label></div><label className="mt-3 block text-xs text-ctp-subtext1">Trading notes<textarea rows={2} value={settings.notes} onChange={(event) => setSettings({ ...settings, notes: event.target.value })} className="mt-1 block w-full rounded-lg border border-ctp-surface1 bg-ctp-base p-3" /></label><Button className="mt-3" disabled={busy} onClick={() => void act(() => accountApi.saveBinderSettings(settings), "Binder settings saved.")}>Save settings</Button></Panel></details>
      <div className="grid gap-3 sm:grid-cols-2"><label className="text-sm">Search binder<input type="search" value={filter} onChange={event => setNameFilter(event.target.value)} className="mt-1 min-h-12 w-full rounded-lg border border-ctp-surface1 bg-ctp-base px-3" /></label><label className="text-sm">Set<select value={setFilter} onChange={event => setSetFilter(event.target.value)} className="mt-1 min-h-12 w-full rounded-lg border border-ctp-surface1 bg-ctp-base px-3"><option value="">All sets</option>{[...new Set(visibleItems.map(item => item.setPrefix).filter(Boolean))].sort().map(set => <option key={set} value={set!}>{set}</option>)}</select></label></div>
      {(["available", "wanted"] as const).map((group) => <div key={group}><h2 className="text-lg font-semibold capitalize">{group} ({visibleItems.filter(item => item.kind === group).length})</h2><div className="mt-3 grid grid-cols-2 gap-3 sm:grid-cols-3 lg:grid-cols-4">{visibleItems.filter((item) => item.kind === group && item.cardName.toLowerCase().includes(filter.toLowerCase()) && (!setFilter || item.setPrefix === setFilter)).map((item) => <ItemRow cards={cards} key={item.id} item={item} onEdit={() => setEditor(items.find(row => row.id === item.id) ?? item)} onDelete={() => void act(() => accountApi.deleteBinderItem(item.id), "Card removed.")} />)}</div>{!visibleItems.some((item) => item.kind === group && item.cardName.toLowerCase().includes(filter.toLowerCase()) && (!setFilter || item.setPrefix === setFilter)) && <p className="mt-2 text-sm text-ctp-subtext0">No {group} cards{filter || setFilter ? " match these filters" : " yet"}.</p>}</div>)}</TabPanel>
    <TabPanel baseId="trading" tab="matches" active={tab} className="mt-5">{matchLoading ? <p role="status">Finding matches…</p> : matchError ? <div role="alert"><p>{matchError}</p><Button onClick={() => void loadMatches()}>Retry</Button></div> : matches.length ? <div className="grid gap-4 sm:grid-cols-2">{matches.map((binder) => <Panel key={binder.owner.profileSlug} padding="sm"><h2 className="font-semibold"><Link to={`/users/${binder.owner.profileSlug}`} className="text-ctp-blue hover:underline">{binder.owner.displayName}</Link></h2><p className="mt-1 text-xs text-ctp-subtext0">{binder.settings.tradeMethod} · {binder.settings.location || "Location not listed"}</p><p className="mt-3 text-sm">{binder.items.filter((item) => item.kind === "available").length} available · {binder.items.filter((item) => item.kind === "wanted").length} wanted</p>{(["available", "wanted"] as const).map(kind => <div key={kind} className="mt-3"><h3 className="text-sm font-semibold">{kind === "available" ? "They have your wants" : "You have theirs"}</h3><div className="mt-2 grid grid-cols-2 gap-2">{binder.items.filter(item => item.kind === kind && visibleItems.some(own => (kind === "available" ? binderItemsMatch(item, own) : binderItemsMatch(own, item)))).slice(0, 4).map(item => <CardResult key={item.id} card={cards.find(card => card.uuid === item.cardUuid)} name={item.cardName} editionUuid={item.editionUuid ?? undefined}><p className="text-xs">{item.kind === "wanted" && (!item.finish || item.finish === "unspecified") ? "Any finish" : finishLabel(item.finish)}</p></CardResult>)}</div></div>)}<Button className="mt-3" onClick={() => { setPartner(binder); setSelected({}); setMessage(""); setNotice(null); }}>Build offer</Button></Panel>)}</div> : <p className="rounded-xl border border-dashed border-ctp-surface1 p-8 text-center text-sm text-ctp-subtext1">No reciprocal matches yet. Add both Available and Wanted cards, then check again.</p>}
      {partner && <DialogSheet title={`Offer with ${partner.owner.displayName}`} onDismiss={() => setPartner(null)} dirty={Object.values(selected).some(value => value > 0) || !!message} dismissible={!busy} footer={<>{notice && <p role="status" className="mb-2 text-sm">{notice}</p>}<Button disabled={busy || !Object.values(selected).some(value => value > 0) || Object.values(selected).some(value => !Number.isInteger(value) || value < 0) || offerItems.some(item => (selected[item.id] ?? 0) > item.quantity - item.reservedQuantity)} onClick={() => void act(() => accountApi.createTrade(partner.owner.profileSlug, offerItems.filter(item => selected[item.id] > 0).map(item => ({ binderItemId: item.id, quantity: selected[item.id] })), message), "Offer sent.").then(success => { if (success) { setPartner(null); setTab("offers"); } })}>Send offer</Button></>}>
        {([true, false]).map(mine => <div key={String(mine)} className="mb-4"><h3 className="mb-2 font-semibold">{mine ? "You give" : "You receive"}</h3><div className="grid grid-cols-1 gap-3 sm:grid-cols-2">{(mine ? ownAvailable : partner.items.filter(item => item.kind === "available" && item.quantity > item.reservedQuantity)).map(item => <CardResult compactOnMobile key={item.id} card={cards.find(card => card.uuid === item.cardUuid)} name={item.cardName} editionUuid={item.editionUuid ?? undefined} newTab><p className="text-sm">{finishLabel(item.finish)}</p><label className="block text-sm">Quantity · {item.quantity - item.reservedQuantity} available<input disabled={busy} aria-label={`${mine ? "Give" : "Receive"} ${item.cardName}`} type="number" min={0} max={item.quantity - item.reservedQuantity} value={selected[item.id] ?? 0} onChange={event => setSelected(current => ({ ...current, [item.id]: Number(event.target.value) }))} className="mt-1 min-h-12 w-full rounded-lg border border-ctp-surface1 bg-ctp-base px-3" /></label></CardResult>)}</div></div>)}
        <label className="block text-sm">Message<textarea disabled={busy} rows={3} value={message} onChange={event => setMessage(event.target.value)} className="mt-1 block w-full rounded-lg border border-ctp-surface1 bg-ctp-base p-3" /></label>
      </DialogSheet>}</TabPanel>
    <TabPanel baseId="trading" tab="offers" active={tab} className="mt-5 space-y-4">{trades.map((trade) => <TradeCard cards={cards} key={trade.id} trade={trade} me={user} refresh={refresh} />)}{trades.length === 0 && <p className="rounded-xl border border-dashed border-ctp-surface1 p-8 text-center text-sm text-ctp-subtext1">No trade offers yet.</p>}</TabPanel>
  </section>;
}
