import { useCallback, useEffect, useMemo, useState } from "react";
import { Link } from "react-router-dom";
import type { AccountUser, BinderItem, BinderItemKind, BinderSettings, CollectionEntry, PublicBinder, Trade, TradeStatus } from "@gatcg/shared";
import { accountApi } from "../../lib/accountApi";
import { useCardCatalog } from "../cards/useCardCatalog";
import Panel from "../../components/ui/Panel";
import Button from "../../components/ui/Button";

const EMPTY_SETTINGS: BinderSettings = { public: false, tradeMethod: "either", location: "", notes: "", updatedAt: null };

function ItemRow({ item, onDelete, selectable, selected, onSelect }: { item: BinderItem; onDelete?: () => void; selectable?: boolean; selected?: boolean; onSelect?: (checked: boolean) => void }) {
  return <article className="flex items-start gap-3 rounded-xl border border-ctp-surface1 bg-ctp-base p-3">
    {selectable && <input type="checkbox" checked={selected} onChange={(event) => onSelect?.(event.target.checked)} className="mt-1 h-5 w-5" aria-label={`Select ${item.cardName}`} />}
    <div className="min-w-0 flex-1"><p className="font-semibold text-ctp-text">{item.cardName}</p><p className="mt-1 text-xs text-ctp-subtext0">{item.setPrefix ? `${item.setPrefix}${item.collectorNumber ? ` #${item.collectorNumber}` : ""}` : "Any printing"} · {item.condition} · {item.language}</p><p className="mt-1 text-xs text-ctp-subtext1">{item.quantity - item.reservedQuantity} available{item.reservedQuantity ? ` · ${item.reservedQuantity} reserved` : ""}</p></div>
    {onDelete && <button type="button" onClick={onDelete} className="min-h-10 rounded-lg px-2 text-xs text-ctp-red hover:bg-ctp-red/10">Remove</button>}
  </article>;
}

function TradeCard({ trade, me, refresh }: { trade: Trade; me: AccountUser; refresh: () => Promise<void> }) {
  const [busy, setBusy] = useState(false), [notice, setNotice] = useState<string | null>(null);
  const mine = trade.sender.profileSlug === me.profileSlug;
  const partner = mine ? trade.recipient : trade.sender;
  const act = async (status: TradeStatus | "sent" | "received") => { setBusy(true); setNotice(null); try { await accountApi.updateTradeStatus(trade.id, status); await refresh(); } catch (error) { setNotice(error instanceof Error ? error.message : "Trade could not be updated"); } finally { setBusy(false); } };
  const counter = async () => { const message = window.prompt("Message with your counteroffer", trade.currentRevision.message) ?? ""; const lines = trade.currentRevision.lines.map((line) => { const entered = window.prompt(`Quantity for ${line.cardName}`, String(line.quantity)); return { binderItemId: line.binderItemId, quantity: Math.max(1, Number(entered) || line.quantity) }; }); setBusy(true); setNotice(null); try { await accountApi.counterTrade(trade.id, lines, message); await refresh(); } catch (error) { setNotice(error instanceof Error ? error.message : "Counteroffer could not be sent"); } finally { setBusy(false); } };
  const open = ["sent", "countered"].includes(trade.status), active = ["accepted", "sender_sent", "recipient_sent", "both_sent"].includes(trade.status);
  return <Panel padding="sm"><div className="flex flex-wrap items-start justify-between gap-2"><div><p className="font-semibold">Trade with <Link to={`/users/${partner.profileSlug}`} className="text-ctp-blue hover:underline">{partner.displayName}</Link></p><p className="mt-1 text-xs uppercase tracking-wide text-ctp-yellow">{trade.status.replaceAll("_", " ")}</p></div><span className="text-xs text-ctp-subtext0">{new Date(trade.updatedAt).toLocaleDateString()}</span></div>
    <div className="mt-3 grid gap-2 sm:grid-cols-2">{(["sender_gives", "recipient_gives"] as const).map((direction) => <div key={direction} className="rounded-lg bg-ctp-surface0 p-3"><p className="text-xs font-semibold text-ctp-subtext1">{direction === "sender_gives" ? `${trade.sender.displayName} gives` : `${trade.recipient.displayName} gives`}</p>{trade.currentRevision.lines.filter((line) => line.direction === direction).map((line) => <p key={line.binderItemId} className="mt-1 text-sm">{line.quantity}× {line.cardName}</p>)}</div>)}</div>
    {trade.currentRevision.message && <p className="mt-3 text-sm text-ctp-subtext1">“{trade.currentRevision.message}”</p>}
    <div className="mt-3 flex flex-wrap gap-2">{open && <><Button disabled={busy} onClick={() => void act("accepted")}>Accept</Button><Button variant="secondary" disabled={busy} onClick={() => void counter()}>Counter</Button><Button variant="secondary" disabled={busy} onClick={() => void act("declined")}>Decline</Button>{mine && <Button variant="secondary" disabled={busy} onClick={() => void act("cancelled")}>Cancel</Button>}</>}{active && trade.status !== "both_sent" && <Button disabled={busy} onClick={() => void act("sent")}>Mark my cards sent</Button>}{trade.status === "both_sent" && <Button disabled={busy} onClick={() => void act("received")}>Confirm received</Button>}{active && <Button variant="secondary" disabled={busy} onClick={() => void act("disputed")}>Report a problem</Button>}</div>{notice && <p className="mt-2 text-xs text-ctp-yellow">{notice}</p>}
  </Panel>;
}

export default function TradingBinder({ publicSlug }: { publicSlug?: string } = {}) {
  const cards = useCardCatalog();
  const [user, setUser] = useState<AccountUser | null>();
  const [settings, setSettings] = useState(EMPTY_SETTINGS), [items, setItems] = useState<BinderItem[]>([]), [collection, setCollection] = useState<CollectionEntry[]>([]);
  const [matches, setMatches] = useState<PublicBinder[]>([]), [trades, setTrades] = useState<Trade[]>([]), [tab, setTab] = useState<"binder" | "matches" | "offers">("binder");
  const [kind, setKind] = useState<BinderItemKind>("available"), [cardUuid, setCardUuid] = useState(""), [editionUuid, setEditionUuid] = useState(""), [quantity, setQuantity] = useState(1);
  const [partner, setPartner] = useState<PublicBinder | null>(null), [selected, setSelected] = useState<Record<string, boolean>>({}), [message, setMessage] = useState("");
  const [publicView, setPublicView] = useState<PublicBinder | null>();
  const [busy, setBusy] = useState(false), [notice, setNotice] = useState<string | null>(null);
  const refresh = useCallback(async () => { const [binder, tradeResult] = await Promise.all([accountApi.binder(), accountApi.trades()]); setSettings(binder.settings); setItems(binder.items); setTrades(tradeResult.trades); }, []);
  useEffect(() => { if (publicSlug) { void accountApi.publicBinder(publicSlug).then(({ binder }) => setPublicView(binder)).catch(() => setPublicView(null)); return; } void accountApi.session().then(async ({ user: result }) => { setUser(result); if (result) { const collectionResult = await accountApi.collection(); setCollection(collectionResult.entries); await refresh(); } }).catch(() => setUser(null)); }, [refresh, publicSlug]);
  const card = cards.find((candidate) => candidate.uuid === cardUuid);
  const availableSources = useMemo(() => collection.filter((entry) => entry.ownedQuantity > 0), [collection]);
  const act = async (action: () => Promise<unknown>, success: string) => { setBusy(true); setNotice(null); try { await action(); await refresh(); setNotice(success); } catch (error) { setNotice(error instanceof Error ? error.message : "Action failed"); } finally { setBusy(false); } };
  if (publicSlug) return publicView === undefined ? <Panel className="mt-6">Loading binder…</Panel> : publicView ? <section className="mt-6"><Panel padding="sm"><h2 className="text-lg font-semibold">{publicView.owner.displayName}’s binder</h2><p className="mt-1 text-sm text-ctp-subtext1">{publicView.settings.tradeMethod} · {publicView.settings.location || "Location not listed"}</p>{publicView.settings.notes && <p className="mt-3 text-sm">{publicView.settings.notes}</p>}</Panel>{(["available", "wanted"] as const).map((group) => <div key={group} className="mt-6"><h2 className="text-lg font-semibold capitalize">{group}</h2><div className="mt-3 grid gap-3 sm:grid-cols-2">{publicView.items.filter((item) => item.kind === group).map((item) => <ItemRow key={item.id} item={item} />)}</div></div>)}</section> : <Panel className="mt-6">This binder is private or unavailable.</Panel>;
  if (user === undefined) return <Panel className="mt-6">Loading your trading binder…</Panel>;
  if (!user) return <Panel className="mt-6"><h2 className="text-lg font-semibold">Trading binder</h2><p className="mt-2 text-sm text-ctp-subtext1">Sign in to publish cards, find reciprocal matches, and make auditable trade offers.</p><Link to="/account" className="mt-4 inline-flex min-h-11 items-center rounded-lg bg-ctp-blue px-4 text-sm font-semibold text-ctp-base">Sign in</Link></Panel>;
  const ownAvailable = items.filter((item) => item.kind === "available");
  const offerItems = partner ? [...ownAvailable, ...partner.items.filter((item) => item.kind === "available" && item.quantity > item.reservedQuantity)] : [];
  return <section className="mt-6">
    <div className="flex overflow-x-auto rounded-xl border border-ctp-surface1 bg-ctp-mantle p-1" role="tablist">{(["binder", "matches", "offers"] as const).map((value) => <button key={value} type="button" role="tab" aria-selected={tab === value} onClick={() => { setTab(value); if (value === "matches") void accountApi.binderMatches().then((result) => setMatches(result.binders)); }} className={`min-h-11 flex-1 whitespace-nowrap rounded-lg px-4 text-sm font-medium ${tab === value ? "bg-ctp-blue text-ctp-base" : "text-ctp-subtext1"}`}>{value === "binder" ? "My Binder" : value === "matches" ? "Matches" : `Offers (${trades.length})`}</button>)}</div>
    {notice && <p role="status" className="mt-3 rounded-lg bg-ctp-surface0 p-3 text-sm text-ctp-yellow">{notice}</p>}
    {tab === "binder" && <div className="mt-5 space-y-5"><Panel><h2 className="font-semibold">Visibility and trading</h2><label className="mt-3 flex items-start gap-3 text-sm"><input type="checkbox" checked={settings.public} onChange={(event) => setSettings({ ...settings, public: event.target.checked })} className="mt-1 h-5 w-5" /><span><span className="font-medium">Publish my binder</span><br /><span className="text-ctp-subtext0">Only quantities listed as Available are shown.</span></span></label><div className="mt-4 grid gap-3 sm:grid-cols-2"><label className="text-xs text-ctp-subtext1">Trade method<select value={settings.tradeMethod} onChange={(event) => setSettings({ ...settings, tradeMethod: event.target.value as BinderSettings["tradeMethod"] })} className="mt-1 block min-h-11 w-full rounded-lg border border-ctp-surface1 bg-ctp-base px-3"><option value="either">Local or shipping</option><option value="local">Local only</option><option value="shipping">Shipping only</option></select></label><label className="text-xs text-ctp-subtext1">General location<input value={settings.location} onChange={(event) => setSettings({ ...settings, location: event.target.value })} placeholder="City, region, or country" className="mt-1 block min-h-11 w-full rounded-lg border border-ctp-surface1 bg-ctp-base px-3" /></label></div><label className="mt-3 block text-xs text-ctp-subtext1">Trading notes<textarea rows={2} value={settings.notes} onChange={(event) => setSettings({ ...settings, notes: event.target.value })} className="mt-1 block w-full rounded-lg border border-ctp-surface1 bg-ctp-base p-3" /></label><Button className="mt-3" disabled={busy} onClick={() => void act(() => accountApi.saveBinderSettings(settings), "Binder settings saved.")}>Save settings</Button></Panel>
      <Panel><h2 className="font-semibold">Add a card</h2><div className="mt-3 grid gap-3 sm:grid-cols-2"><label className="text-xs text-ctp-subtext1">List<select value={kind} onChange={(event) => { setKind(event.target.value as BinderItemKind); setCardUuid(""); setEditionUuid(""); }} className="mt-1 block min-h-11 w-full rounded-lg border border-ctp-surface1 bg-ctp-base px-3"><option value="available">Available</option><option value="wanted">Wanted</option></select></label><label className="text-xs text-ctp-subtext1">Card<select value={kind === "available" ? `${cardUuid}|${editionUuid}` : cardUuid} onChange={(event) => { const [uuid, edition = ""] = event.target.value.split("|"); setCardUuid(uuid); setEditionUuid(edition); }} className="mt-1 block min-h-11 w-full rounded-lg border border-ctp-surface1 bg-ctp-base px-3"><option value="">Choose a card</option>{kind === "available" ? availableSources.map((entry) => <option key={`${entry.cardUuid}|${entry.editionUuid ?? ""}`} value={`${entry.cardUuid}|${entry.editionUuid ?? ""}`}>{entry.cardName}{entry.setPrefix ? ` (${entry.setPrefix} #${entry.collectorNumber ?? "?"})` : ""} · {entry.ownedQuantity} owned</option>) : cards.map((entry) => <option key={entry.uuid} value={entry.uuid}>{entry.name}</option>)}</select></label><label className="text-xs text-ctp-subtext1">Quantity<input type="number" min={1} max={999} value={quantity} onChange={(event) => setQuantity(Number(event.target.value))} className="mt-1 block min-h-11 w-full rounded-lg border border-ctp-surface1 bg-ctp-base px-3" /></label>{kind === "wanted" && card && <label className="text-xs text-ctp-subtext1">Preferred printing<select value={editionUuid} onChange={(event) => setEditionUuid(event.target.value)} className="mt-1 block min-h-11 w-full rounded-lg border border-ctp-surface1 bg-ctp-base px-3"><option value="">Any printing</option>{card.editions.map((edition) => <option key={edition.uuid} value={edition.uuid}>{edition.set.prefix} #{edition.collector_number}</option>)}</select></label>}</div><Button className="mt-3" disabled={busy || !cardUuid || quantity < 1} onClick={() => { const source = kind === "available" ? availableSources.find((entry) => entry.cardUuid === cardUuid && (entry.editionUuid ?? "") === editionUuid) : undefined; const selectedCard = cards.find((entry) => entry.uuid === cardUuid); const edition = selectedCard?.editions.find((entry) => entry.uuid === editionUuid); void act(() => accountApi.addBinderItem({ kind, cardUuid, cardName: source?.cardName ?? selectedCard?.name ?? "", editionUuid: editionUuid || null, setPrefix: source?.setPrefix ?? edition?.set.prefix ?? null, collectorNumber: source?.collectorNumber ?? edition?.collector_number ?? null, quantity, condition: "Any", language: "Any", acceptsAlternatives: true }), "Card added to binder."); }}>Add card</Button></Panel>
      {(["available", "wanted"] as const).map((group) => <div key={group}><h2 className="text-lg font-semibold capitalize">{group}</h2><div className="mt-3 grid gap-3 sm:grid-cols-2">{items.filter((item) => item.kind === group).map((item) => <ItemRow key={item.id} item={item} onDelete={() => void act(() => accountApi.deleteBinderItem(item.id), "Card removed.")} />)}</div>{!items.some((item) => item.kind === group) && <p className="mt-2 text-sm text-ctp-subtext0">No {group} cards yet.</p>}</div>)}</div>}
    {tab === "matches" && <div className="mt-5">{matches.length ? <div className="grid gap-4 sm:grid-cols-2">{matches.map((binder) => <Panel key={binder.owner.profileSlug} padding="sm"><h2 className="font-semibold"><Link to={`/users/${binder.owner.profileSlug}`} className="text-ctp-blue hover:underline">{binder.owner.displayName}</Link></h2><p className="mt-1 text-xs text-ctp-subtext0">{binder.settings.tradeMethod} · {binder.settings.location || "Location not listed"}</p><p className="mt-3 text-sm">{binder.items.filter((item) => item.kind === "available").length} available · {binder.items.filter((item) => item.kind === "wanted").length} wanted</p><Button className="mt-3" onClick={() => { setPartner(binder); setSelected({}); }}>Build offer</Button></Panel>)}</div> : <p className="rounded-xl border border-dashed border-ctp-surface1 p-8 text-center text-sm text-ctp-subtext1">No reciprocal matches yet. Add both Available and Wanted cards, then check again.</p>}
      {partner && <Panel className="mt-5"><h2 className="font-semibold">Offer with {partner.owner.displayName}</h2><p className="mt-1 text-xs text-ctp-subtext0">Select cards from either binder. Quantities default to one.</p><div className="mt-3 grid gap-3 sm:grid-cols-2">{offerItems.map((item) => <ItemRow key={item.id} item={item} selectable selected={Boolean(selected[item.id])} onSelect={(checked) => setSelected((current) => ({ ...current, [item.id]: checked }))} />)}</div><label className="mt-3 block text-xs text-ctp-subtext1">Message<textarea rows={3} value={message} onChange={(event) => setMessage(event.target.value)} className="mt-1 block w-full rounded-lg border border-ctp-surface1 bg-ctp-base p-3" /></label><Button className="mt-3" disabled={busy || !Object.values(selected).some(Boolean)} onClick={() => void act(() => accountApi.createTrade(partner.owner.profileSlug, offerItems.filter((item) => selected[item.id]).map((item) => ({ binderItemId: item.id, quantity: 1 })), message), "Offer sent.").then(() => { setPartner(null); setTab("offers"); })}>Send offer</Button></Panel>}</div>}
    {tab === "offers" && <div className="mt-5 space-y-4">{trades.map((trade) => <TradeCard key={trade.id} trade={trade} me={user} refresh={refresh} />)}{trades.length === 0 && <p className="rounded-xl border border-dashed border-ctp-surface1 p-8 text-center text-sm text-ctp-subtext1">No trade offers yet.</p>}</div>}
  </section>;
}
