import { parseCostModifierRules, type Card } from "@gatcg/shared";
import CostBreakdown from "../../components/CostBreakdown";
import type { ComboRecipeRequirement } from "../deckbuilder/HypergeometricCalculator";

export default function ComboCostAssumptions({ requirements, catalogByName, costs, onChange }: { requirements: ComboRecipeRequirement[]; catalogByName: Map<string, Card>; costs: Record<string, number>; onChange: (costs: Record<string, number>) => void }) {
  const names = [...new Set(requirements.flatMap((requirement) => requirement.kind === "cards" ? requirement.cards : []))];
  const cards = names.map((name) => catalogByName.get(name)).filter((card): card is Card => Boolean(card?.cost_reserve != null));
  if (cards.length === 0) return null;
  const printedTotal = cards.reduce((sum, card) => sum + card.cost_reserve!, 0);
  const effectiveTotal = cards.reduce((sum, card) => sum + (costs[card.name] ?? card.cost_reserve!), 0);
  return <details className="mt-4 rounded-xl border border-ctp-surface1 bg-ctp-mantle p-3"><summary className="flex min-h-11 cursor-pointer items-center justify-between gap-2 text-sm font-semibold text-ctp-text"><span>Combo affordability assumptions ({cards.length})</span><span className="text-xs tabular-nums text-ctp-green">{printedTotal} → {effectiveTotal} Reserve</span></summary><p className="mt-1 text-xs text-ctp-subtext0">Access odds remain separate. Set each piece's cost to inspect printed reductions before deciding whether the whole line is affordable.</p><div className="mt-3 grid gap-2 sm:grid-cols-2">{cards.map((card) => { const printed = card.cost_reserve!; const rules = parseCostModifierRules(card); return <article key={card.name} className="rounded-lg border border-ctp-surface1 bg-ctp-base/35 p-3"><label className="grid grid-cols-[1fr_5rem] items-center gap-2 text-xs text-ctp-subtext1"><span className="font-medium text-ctp-text">{card.name}</span><input aria-label={`Effective Reserve cost for ${card.name} in combo`} type="number" min={0} max={99} value={costs[card.name] ?? printed} onChange={(event) => onChange({ ...costs, [card.name]: Math.max(0, Math.round(Number(event.target.value) || 0)) })} className="min-h-11 rounded-lg border border-ctp-surface1 bg-ctp-base px-2 text-sm text-ctp-text" /></label><CostBreakdown card={card} effectiveCost={costs[card.name]} compact />{rules.length === 0 && <p className="mt-1 text-[10px] text-ctp-subtext0">No printed reduction detected.</p>}</article>; })}</div><p className="mt-2 text-[10px] leading-4 text-ctp-subtext0">The total counts one of each explicitly named piece. Costs are additive for this scenario. This does not model payment order, shared resources, alternative pieces, or prove that conditional reductions are active.</p></details>;
}
