/** Generate reviewable seed SQL from local archives; never connects to production. */
import { readFile, readdir, writeFile } from "node:fs/promises";
import { createHash } from "node:crypto";
import { fileURLToPath } from "node:url";
import { canonicalizeSavedDecklist, savedDeckIdentityInput, type OmnidexDecklist } from "@gatcg/shared";

const root = new URL("../../", import.meta.url);
const hash = (s: string) => createHash("sha256").update(s).digest("hex");
const quote = (v: string) => `'${v.replaceAll("'", "''")}'`;
const now = "strftime('%Y-%m-%dT%H:%M:%fZ', 'now')";
type Line = { name: string; quantity: number };
type Candidate = { core: string; champion: string; format: string; decklist: OmnidexDecklist; provenance: unknown; date: string };
const candidates: Candidate[] = [];
for (const provider of ["shoutatyourdecks", "tcgarchitect", "sleeved"]) {
  const directory = new URL(`data/${provider}/decks/`, root);
  for (const filename of (await readdir(directory)).filter((f) => f.endsWith(".json")).sort()) {
    const d = JSON.parse(await readFile(new URL(filename, directory), "utf8"));
    if (!["STANDARD", "PANTHEON"].includes(d.format) || !d.champion) continue;
    const raw: Line[][] = [d.mainDeck, d.materialDeck, d.sideDeck ?? []];
    if (!raw.every((s) => Array.isArray(s) && s.every((l) => typeof l.name === "string" && l.name.trim() && Number.isInteger(l.quantity) && l.quantity > 0 && l.quantity <= 100))) continue;
    const counts = raw.map((s) => s.reduce((n, l) => n + l.quantity, 0));
    // Conservative size screen, not a claim of current format legality.
    if (counts[0] < 60 || counts[0] > 70 || counts[1] < 1 || counts[1] > 12 || counts[2] > 15) continue;
    const [main, material, sideboard] = raw.map((s) => s.map((l) => ({ card: l.name, quantity: l.quantity })));
    const decklist = canonicalizeSavedDecklist({ main, material, sideboard });
    const champion = String(d.champion).split(",")[0].trim().replace(/\b\w/g, (c) => c.toUpperCase());
    candidates.push({ core: hash(savedDeckIdentityInput(decklist)), champion, format: d.format, decklist,
      date: d.updatedAt ?? d.createdAt ?? "",
      provenance: { provider, externalDeckId: d.id, sourceUrl: d.url, originalTitle: d.title, author: d.author, fetchedAt: d.fetchedAt } });
  }
}
// Round-robin champion/format buckets so a popular champion cannot fill the library.
candidates.sort((a, b) => b.date.localeCompare(a.date) || a.core.localeCompare(b.core));
const buckets = new Map<string, Candidate[]>();
const seen = new Set<string>();
for (const c of candidates) {
  if (seen.has(c.core)) continue;
  seen.add(c.core);
  const key = `${c.format}:${c.champion}`;
  buckets.set(key, [...(buckets.get(key) ?? []), c]);
}
const selected: Candidate[] = [];
const ordered = [...buckets.entries()].sort(([a], [b]) => a.localeCompare(b));
for (let round = 0; selected.length < 60; round++) {
  const batch = ordered.flatMap(([, entries]) => entries[round] ? [entries[round]] : []);
  if (!batch.length) break;
  selected.push(...batch.slice(0, 60 - selected.length));
}
if (selected.length < 50) throw new Error(`Only ${selected.length} candidates passed the screen`);
const owner = "fanofin-starter-library";
const sql = ["-- Generated by scripts/build-starter-library.ts. Review before applying.\n-- No login credentials, fabricated engagement, or public source metadata.\nPRAGMA foreign_keys = ON;",
  `INSERT INTO users (id, google_subject, email, display_name, profile_slug, is_system, created_at, updated_at) VALUES (${quote(owner)}, 'system:starter-library', 'starter-library@fanofin.invalid', 'Fan of Insight', '${hash(owner).slice(0, 24)}', 1, ${now}, ${now}) ON CONFLICT(id) DO NOTHING;`];
const titleCounts = new Map<string, number>();
for (const c of selected) {
  const id = `seed:${c.core}`;
  const version = `${id}:v1`;
  const full = hash(JSON.stringify({ format: c.format, championName: c.champion.toLocaleLowerCase("en-US"), decklist: c.decklist }));
  const titleKey = `${c.champion} · ${c.format === "PANTHEON" ? "Pantheon" : "Standard"}`;
  const number = (titleCounts.get(titleKey) ?? 0) + 1; titleCounts.set(titleKey, number);
  const title = `${titleKey} · Build ${number}`;
  const description = "A curated starting point to copy and customize. Check current format legality before tournament play.";
  const list = quote(JSON.stringify(c.decklist));
  sql.push(
    `INSERT INTO canonical_builds (id, core_identity_hash, full_identity_hash, format, champion_name, decklist_json, created_at) VALUES ('${full}', '${c.core}', '${full}', ${quote(c.format)}, ${quote(c.champion)}, ${list}, ${now}) ON CONFLICT(full_identity_hash) DO NOTHING;`,
    `INSERT INTO saved_decks (id, user_id, identity_hash, title, format, champion_name, decklist_json, created_at, updated_at) VALUES (${quote(id)}, ${quote(owner)}, '${c.core}', ${quote(title)}, ${quote(c.format)}, ${quote(c.champion)}, ${list}, ${now}, ${now}) ON CONFLICT(id) DO NOTHING;`,
    `INSERT INTO user_decks (id, owner_user_id, public_slug, title, description, visibility, format, champion_name, current_version_id, published_version_id, published_title, published_description, published_primer_markdown, published_tags_json, is_seed, published_at, created_at, updated_at) VALUES (${quote(id)}, ${quote(owner)}, '${hash(id).slice(0, 32)}', ${quote(title)}, ${quote(description)}, 'public', ${quote(c.format)}, ${quote(c.champion)}, ${quote(version)}, ${quote(version)}, ${quote(title)}, ${quote(description)}, '', '["Starter Library"]', 1, ${now}, ${now}, ${now}) ON CONFLICT(id) DO NOTHING;`,
    `INSERT INTO deck_versions (id, deck_id, version_number, canonical_build_id, change_note, created_at) VALUES (${quote(version)}, ${quote(id)}, 1, (SELECT id FROM canonical_builds WHERE full_identity_hash = '${full}'), 'Starter Library', ${now}) ON CONFLICT(id) DO NOTHING;`,
    `INSERT INTO starter_library_sources (deck_id, provenance_json) VALUES (${quote(id)}, ${quote(JSON.stringify(c.provenance))}) ON CONFLICT(deck_id) DO NOTHING;`,
  );
}
const output = new URL("account-worker/seeds/starter-library.sql", root);
await writeFile(output, sql.join("\n") + "\n");
console.log(`Wrote ${selected.length} unique builds across ${new Set(selected.map((c) => c.champion)).size} champions to ${fileURLToPath(output)}`);
