import type { Card } from "@gatcg/shared";
import CardImage from "../../components/CardImage";
import { activeAnalysisPlan, addAnalysisPlan, removeAnalysisPlan, type DeckAnalysisProfile, type StageUsefulness } from "../../lib/analysisProfile";
import type { GamePlanRole } from "../../lib/gamePlanReadiness";

interface Line { name: string; quantity: number }
const LABEL: Record<GamePlanRole, string> = { enabler: "Setup", payoff: "Payoff", protection: "Protection" };
const STAGE: Record<StageUsefulness, string> = { early: "Early", late: "Late", flexible: "Any stage", conditional: "Conditional" };

export default function PrepareAnalysis({ lines, catalogByName, profile, onProfileChange, onReviewed }: { lines: Line[]; catalogByName: Map<string, Card>; profile: DeckAnalysisProfile; onProfileChange: (profile: DeckAnalysisProfile) => void; onReviewed: () => void }) {
  const plan = activeAnalysisPlan(profile); const roles = plan.roles;
  const counts = { enabler: 0, payoff: 0, protection: 0 };
  for (const line of lines) { const role = roles[line.name]; if (role) counts[role] += line.quantity; }
  const assigned = lines.filter((line) => roles[line.name]).length; const ready = counts.enabler > 0 && counts.payoff > 0;
  const updatePlan = (change: Partial<typeof plan>) => onProfileChange({ ...profile, plans: profile.plans.map((item) => item.id === plan.id ? { ...item, ...change } : item), reviewedAt: null });
  return <details className="group rounded-xl border border-ctp-blue/40 bg-ctp-blue/5" open={!ready || !profile.reviewedAt}>
    <summary className="flex min-h-14 cursor-pointer list-none items-center justify-between gap-3 p-3 focus-visible:ring-2 focus-visible:ring-inset focus-visible:ring-ctp-blue"><span><span className="block text-sm font-semibold text-ctp-text">Prepare analysis</span><span className="mt-0.5 block text-xs text-ctp-subtext0">{ready ? `${plan.name} · ${assigned} cards classified` : "Define a named plan once; calculators reuse it"}</span></span><span className={`rounded-full px-2 py-1 text-[10px] font-semibold ${ready && profile.reviewedAt ? "bg-ctp-green/15 text-ctp-green" : "bg-ctp-yellow/15 text-ctp-yellow"}`}>{ready && profile.reviewedAt ? "Reviewed" : "Needs review"}</span></summary>
    <div className="border-t border-ctp-blue/20 p-3 sm:p-4">
      <div className="grid gap-2 sm:grid-cols-[minmax(0,1fr)_auto_auto]"><label className="text-xs text-ctp-subtext0">Active game plan<select value={profile.activePlanId} onChange={(event) => onProfileChange({ ...profile, activePlanId: event.target.value })} className="mt-1 min-h-11 w-full rounded-lg border border-ctp-surface1 bg-ctp-base px-3 text-sm text-ctp-text">{profile.plans.map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</select></label><button type="button" disabled={profile.plans.length >= 12} onClick={() => onProfileChange(addAnalysisPlan(profile, `Plan ${profile.plans.length + 1}`))} className="min-h-11 self-end rounded-lg border border-ctp-blue/50 px-3 text-xs font-semibold text-ctp-blue disabled:opacity-40">Add plan</button><button type="button" disabled={profile.plans.length <= 1} onClick={() => onProfileChange(removeAnalysisPlan(profile, plan.id))} className="min-h-11 self-end rounded-lg px-3 text-xs font-medium text-ctp-red disabled:opacity-40">Remove</button></div>
      <label className="mt-3 block text-xs text-ctp-subtext0">Plan name<input value={plan.name} maxLength={80} onChange={(event) => updatePlan({ name: event.target.value })} className="mt-1 min-h-11 w-full rounded-lg border border-ctp-surface1 bg-ctp-base px-3 text-sm text-ctp-text" /></label>
      <div className="mt-3 grid grid-cols-3 gap-2">{(["enabler", "payoff", "protection"] as const).map((role) => <div key={role} className="rounded-lg border border-ctp-surface1 bg-ctp-base/50 p-2 text-center"><p className="text-[10px] uppercase tracking-wide text-ctp-subtext0">{LABEL[role]}</p><p className="mt-1 text-lg font-bold text-ctp-text">{counts[role]}</p></div>)}</div>
      <p className="mt-3 text-xs text-ctp-subtext1">Role, stage usefulness, pressure assumptions, and cost overrides persist with this deck version. Switch plans to model competing strategies without overwriting them.</p>
      {profile.inheritedFrom && <p className="mt-2 rounded-lg border border-ctp-yellow/30 bg-ctp-yellow/5 p-2 text-xs text-ctp-subtext1">Unchanged card assignments carried forward from revision {profile.revision - 1}. Review this version before relying on it.</p>}
      <div className="mt-3 max-h-[32rem] space-y-2 overflow-y-auto">{lines.map((line) => { const card = catalogByName.get(line.name); const pressure = plan.pressure[line.name]; return <article key={line.name} className="rounded-xl border border-ctp-surface1 bg-ctp-mantle p-2"><div className="grid grid-cols-[2.25rem_minmax(0,1fr)] items-center gap-2 sm:grid-cols-[2.25rem_minmax(0,1fr)_9rem_9rem]">{card?.editions[0] ? <CardImage image={card.editions[0].image} alt={line.name} className="h-12 w-9 rounded object-cover object-top" /> : <div className="h-12 w-9 rounded bg-ctp-surface0" />}<div className="min-w-0"><p className="truncate text-sm font-medium text-ctp-text">{line.name}</p><p className="text-[10px] text-ctp-subtext0">{line.quantity} copies</p></div><select value={roles[line.name] ?? ""} onChange={(event) => updatePlan({ roles: { ...roles, [line.name]: event.target.value as GamePlanRole | "" } })} aria-label={`Analysis role for ${line.name}`} className="col-span-2 min-h-11 rounded-lg border border-ctp-surface1 bg-ctp-base px-2 text-xs text-ctp-text sm:col-span-1"><option value="">No plan role</option><option value="enabler">Setup</option><option value="payoff">Payoff</option><option value="protection">Protection</option></select><select value={plan.stageUsefulness[line.name] ?? ""} onChange={(event) => updatePlan({ stageUsefulness: { ...plan.stageUsefulness, [line.name]: event.target.value as StageUsefulness | "" } })} aria-label={`Stage usefulness for ${line.name}`} className="col-span-2 min-h-11 rounded-lg border border-ctp-surface1 bg-ctp-base px-2 text-xs text-ctp-text sm:col-span-1"><option value="">Infer from role</option>{Object.entries(STAGE).map(([value, label]) => <option key={value} value={value}>{label}</option>)}</select></div>
        {(roles[line.name] === "payoff" || pressure) && <details className="mt-2"><summary className="flex min-h-11 cursor-pointer items-center text-xs font-medium text-ctp-blue">Pressure assumptions</summary><div className="grid gap-2 sm:grid-cols-3"><label className="text-[10px] text-ctp-subtext0">Earliest useful<input type="number" min={1} max={8} value={pressure?.earliestTurn ?? 1} onChange={(event) => updatePlan({ pressure: { ...plan.pressure, [line.name]: { earliestTurn: Number(event.target.value), repeatable: pressure?.repeatable ?? false, effectiveReserveCost: pressure?.effectiveReserveCost ?? card?.cost_reserve ?? 0 } } })} className="mt-1 min-h-11 w-full rounded-lg border border-ctp-surface1 bg-ctp-base px-2 text-sm" /></label><label className="text-[10px] text-ctp-subtext0">Effective cost<input type="number" min={0} value={pressure?.effectiveReserveCost ?? card?.cost_reserve ?? 0} onChange={(event) => updatePlan({ pressure: { ...plan.pressure, [line.name]: { earliestTurn: pressure?.earliestTurn ?? 1, repeatable: pressure?.repeatable ?? false, effectiveReserveCost: Number(event.target.value) } } })} className="mt-1 min-h-11 w-full rounded-lg border border-ctp-surface1 bg-ctp-base px-2 text-sm" /></label><label className="flex min-h-11 items-center gap-2 self-end text-xs text-ctp-subtext1"><input type="checkbox" checked={pressure?.repeatable ?? false} onChange={(event) => updatePlan({ pressure: { ...plan.pressure, [line.name]: { earliestTurn: pressure?.earliestTurn ?? 1, repeatable: event.target.checked, effectiveReserveCost: pressure?.effectiveReserveCost ?? card?.cost_reserve ?? 0 } } })} />Repeatable</label></div></details>}</article>; })}</div>
      <div className="mt-3 flex flex-wrap gap-2">{ready && <button type="button" onClick={onReviewed} className="min-h-11 rounded-lg bg-ctp-blue px-3 text-xs font-semibold text-ctp-base">Mark reviewed</button>}<span className="self-center text-[10px] text-ctp-subtext0">Profile revision {profile.revision} · {profile.plans.length} plan{profile.plans.length === 1 ? "" : "s"}</span></div>
    </div>
  </details>;
}
