import {useMemo,useState} from 'react';
import {cardLocationState,deckCardRequirements,locationCardKey,type Card,type CollectionEntry,type CollectionCardTracking,type SavedDeck} from '@gatcg/shared';
import CardArtTile from '../../components/CardArtTile';
import CardLocationSummary from './CardLocationSummary';
export default function CardLocationsView({cards,entries,records,decks,onEdit,onDeck,disabled}: {cards:Card[];entries:CollectionEntry[];records:CollectionCardTracking[];decks:SavedDeck[];onEdit:(card:{uuid:string;name:string})=>void;onDeck:(deck:SavedDeck)=>void;disabled?:boolean}) {
 const [query,setQuery]=useState('');const [filter,setFilter]=useState('all');const [limit,setLimit]=useState(24);
 const needs=useMemo(()=>decks.map(deck=>({deck,needs:deckCardRequirements(deck.decklist)})),[decks]);
 const pool=useMemo(()=>{const result=new Map<string,{uuid:string;name:string}>();for(const entry of entries)result.set(entry.cardUuid,{uuid:entry.cardUuid,name:entry.cardName});for(const row of records)result.set(row.cardUuid,{uuid:row.cardUuid,name:row.cardName});for(const card of cards)if(needs.some(row=>row.needs.has(locationCardKey(card.name))))result.set(card.uuid,{uuid:card.uuid,name:card.name});return [...result.values()];},[entries,records,cards,needs]);
 const matches=pool.filter(card=>{const record=records.find(row=>row.cardUuid===card.uuid);const state=cardLocationState(card.uuid,entries,record);return card.name.toLowerCase().includes(query.toLowerCase()) && (filter==='all'||filter==='lent'&&state.lent>0||filter==='assigned'&&state.assigned>0||filter==='unassigned'&&state.unassigned>0||filter==='check'&&(state.excess>0||record?.mightOwn));});
 return <section className="mt-4"><h2 className="text-xl font-semibold">Where are my cards?</h2><p className="mt-1 text-sm text-ctp-subtext1">Choose which deck holds your copies. Other decklists can use the same cards.</p>
 <label className="mt-3 block text-sm">Put cards in a deck<select aria-label="Assign a deck" disabled={disabled} value="" onChange={event=>{const deck=decks.find(deck=>deck.id===event.target.value);if(deck)onDeck(deck);}} className="mt-1 min-h-12 w-full rounded-lg border border-ctp-surface1 bg-ctp-base px-3"><option value="">Choose a deck to review transfers</option>{decks.map(deck=><option key={deck.id} value={deck.id}>{deck.title}</option>)}</select></label>
 <input aria-label="Find card locations" placeholder="Find a card…" value={query} onChange={event=>{setQuery(event.target.value);setLimit(24);}} className="mt-3 min-h-12 w-full rounded-lg border border-ctp-surface1 bg-ctp-base px-3"/>
 <select aria-label="Card location filter" value={filter} onChange={event=>setFilter(event.target.value)} className="my-3 min-h-12 rounded-lg border border-ctp-surface1 bg-ctp-base px-3"><option value="all">All cards</option><option value="assigned">In decks</option><option value="lent">Lent out</option><option value="unassigned">Unassigned</option><option value="check">Needs checking</option></select>
 {!matches.length && <p role="status">No cards in this view.</p>}
 <div className="grid grid-cols-2 gap-3 sm:grid-cols-3 lg:grid-cols-4">{matches.slice(0,limit).map(item=>{const card=cards.find(card=>card.uuid===item.uuid);const record=records.find(row=>row.cardUuid===item.uuid);const usage=needs.filter(row=>row.needs.has(locationCardKey(item.name)));return <article key={item.uuid} className="min-w-0 rounded-xl border border-ctp-surface1 bg-ctp-mantle p-2"><button type="button" disabled={disabled} aria-label={`Locate ${item.name}`} onClick={()=>onEdit(item)} className="block w-full text-left"><CardArtTile card={card} name={item.name}/><span className="flex min-h-12 items-center text-sm font-medium">{item.name}</span></button><p className="text-xs text-ctp-subtext1">Used in {usage.length} decklists</p><CardLocationSummary cardUuid={item.uuid} record={record} entries={entries} decks={decks} disabled={disabled} onClick={()=>onEdit(item)}/></article>;})}</div>
 {matches.length>limit && <button type="button" onClick={()=>setLimit(limit+24)} className="mt-3 min-h-12 px-3 text-ctp-blue">Show more cards</button>}
 </section>;
}
