import {Link} from 'react-router-dom';
import {cardLocationState,deckCardRequirements,locationCardKey,type Card,type CollectionEntry,type CollectionCardTracking,type SavedDeck} from '@gatcg/shared';
import CardArtTile from '../../components/CardArtTile';
export default function DeckLocationCoverage({decks,cards,entries,records,onAssign,disabled}: {decks:SavedDeck[];cards:Card[];entries:CollectionEntry[];records:CollectionCardTracking[];onAssign:(deck:SavedDeck)=>void;disabled?:boolean}) {
 return <section className="mt-4"><h2 className="text-xl font-semibold">Build a deck with your cards</h2><p className="mt-1 text-sm text-ctp-subtext1">Each deck is checked individually. Copies can move between decks; you don’t need a separate playset for every list.</p>{!decks.length && <p className="mt-3">Save a deck to check coverage.</p>}
 <div className="mt-3 grid grid-cols-1 gap-3 sm:grid-cols-2 lg:grid-cols-3">{decks.map(deck=>{
  const requirements=[...deckCardRequirements(deck.decklist).values()];
  const lines=requirements.map(need=>{const card=cards.find(card=>locationCardKey(card.name)===locationCardKey(need.name));const record=records.find(row=>row.cardUuid===card?.uuid);const state=cardLocationState(card?.uuid ?? '',entries,record);const here=record?.assignments?.find(row=>row.deckId===deck.id)?.quantity ?? 0;const available=Math.min(need.quantity,state.available);return {...need,missing:Math.max(0,need.quantity-state.owned),lent:Math.max(0,need.quantity-state.available)-Math.max(0,need.quantity-state.owned),move:Math.max(0,available-here-state.unassigned),excess:state.excess};});
  const missing=lines.reduce((sum,row)=>sum+row.missing,0);const lent=lines.reduce((sum,row)=>sum+row.lent,0);const move=lines.reduce((sum,row)=>sum+row.move,0);
  const art=cards.find(card=>card.name===deck.championName) ?? cards.find(card=>card.name===requirements[0]?.name);
  return <article key={deck.id} className="rounded-xl border border-ctp-surface1 bg-ctp-mantle p-3"><div className="flex gap-3"><div className="w-20 shrink-0"><CardArtTile card={art} name={deck.championName ?? deck.title}/></div><div><h3 className="font-semibold">{deck.title}</h3><p className="mt-2 text-sm">{missing ? `${missing} copies not owned` : 'All required copies owned'}{lent ? ` · ${lent} lent or trade-reserved` : ''}</p>{move>0 && <p className="mt-1 text-sm text-ctp-blue">{move} available in other decks</p>}{lines.some(row=>row.excess>0) && <p className="text-sm text-ctp-yellow">Some card locations need reconciliation.</p>}</div></div><button type="button" disabled={disabled} onClick={()=>onAssign(deck)} className="mt-3 min-h-12 w-full rounded-lg border border-ctp-blue px-3 text-sm text-ctp-blue">Assign deck cards here</button><Link to={`/decks/${encodeURIComponent(deck.id)}`} className="mt-1 flex min-h-12 items-center justify-center text-sm text-ctp-blue underline">Open deck</Link></article>;
 })}</div></section>;
}
