import type { Card, CardStat } from "@gatcg/shared";
import { Link } from "react-router-dom";
import CardHoverPreview from "../../components/CardHoverPreview";
import CostIcon from "../../components/CostIcon";
import { InlineState } from "../../components/ui/ContentState";
import Panel from "../../components/ui/Panel";
import Section from "../../components/ui/Section";
import { earliestReleaseDate, statDiff } from "../../lib/cardSimilarity";

const MIN_SAMPLE_SIZE = 5;
const delta = (value: number | null) => value === null || value === 0 ? "" : ` (${value > 0 ? "+" : ""}${value})`;

export default function CardSimilarEffectsPanel({ card, cardStat, similarCards, resolveReference }: { card: Card; cardStat?: CardStat; similarCards: Card[]; resolveReference: (reference: { slug: string; name: string }) => Card | undefined }) {
  const showReferences = (!cardStat || cardStat.deckCount < MIN_SAMPLE_SIZE) && (card.references.length > 0 || card.referenced_by.length > 0);
  return <Section className="mt-4" heading="compact" title="Same effect shape">
    {showReferences && <Panel padding="sm" className="mt-2"><p className="text-xs text-ctp-subtext0">Too few recorded decks for a trustworthy win rate yet (<Link to="/methodology#small-samples" className="text-ctp-blue hover:underline">learn more</Link>). This card's explicit references are a more reliable signal:</p><div className="mt-2 space-y-2">{[{ title: "References", refs: card.references, showKind: true }, { title: "Referenced by", refs: card.referenced_by, showKind: false }].filter((group) => group.refs.length > 0).map((group) => <div key={group.title}><h3 className="text-xs font-semibold uppercase tracking-wide text-ctp-subtext0">{group.title}</h3><div className="mt-1 flex flex-wrap gap-2 text-sm">{group.refs.map((reference) => <CardHoverPreview key={reference.slug} image={resolveReference(reference)?.editions[0]?.image} alt={reference.name}><Link to={`/cards/${reference.slug}`} className="text-ctp-blue hover:underline">{reference.name}{group.showKind && <span className="text-ctp-subtext0"> ({reference.kind.toLowerCase()})</span>}</Link></CardHoverPreview>)}</div></div>)}</div></Panel>}
    {similarCards.length > 0 ? <><p className="mt-3 text-xs text-ctp-subtext0">Cards with a matching ability template, for comparing cost and stats side by side — deltas are relative to {card.name}.</p><div className="mt-3 overflow-x-auto"><table className="w-max min-w-full text-sm"><thead><tr className="border-b border-ctp-surface1 text-left text-xs uppercase text-ctp-subtext0"><th className="py-1 pr-6">Card</th><th className="py-1 pr-6">Cost</th><th className="py-1 pr-6">Power</th><th className="py-1 pr-6">Life</th><th className="py-1 pr-6">Durability</th><th className="py-1 pr-6">Released</th></tr></thead><tbody className="divide-y divide-ctp-surface0">{similarCards.map((candidate) => { const released = earliestReleaseDate(candidate); const diff = statDiff(card, candidate); return <tr key={candidate.uuid}><td className="whitespace-nowrap py-1.5 pr-6"><CardHoverPreview image={candidate.editions[0]?.image} alt={candidate.name}><Link to={`/cards/${candidate.slug}`} className="text-ctp-text hover:text-ctp-blue">{candidate.name}</Link></CardHoverPreview></td><td className="py-1.5 pr-6 text-ctp-subtext1">{candidate.cost.type !== "none" && candidate.cost.value !== null ? <span className="flex items-center gap-1"><CostIcon kind={candidate.cost.type} size={12} />{candidate.cost.value}{delta(diff.cost)}</span> : "—"}</td><td className="py-1.5 pr-6 text-ctp-subtext1">{candidate.power ?? "—"}{delta(diff.power)}</td><td className="py-1.5 pr-6 text-ctp-subtext1">{candidate.life ?? "—"}{delta(diff.life)}</td><td className="py-1.5 pr-6 text-ctp-subtext1">{candidate.durability ?? "—"}{delta(diff.durability)}</td><td className="py-1.5 pr-6 text-ctp-subtext1">{released ? new Date(released).toLocaleDateString() : "—"}</td></tr>; })}</tbody></table></div></> : <InlineState className="mt-4 text-sm">No other cards share {card.name}'s ability template yet.</InlineState>}
  </Section>;
}
