import type { Card, CardQuantityBucket, CardStat } from "@gatcg/shared";
import { Link } from "react-router-dom";
import CardHoverPreview from "../../components/CardHoverPreview";
import Section from "../../components/ui/Section";

function Metric({ label, value }: { label: string; value: string | number }) {
  return <div className="border-l border-ctp-surface2 pl-4 first:border-l-0 first:pl-0"><p className="text-xs text-ctp-subtext0">{label}</p><p className="mt-1 text-xl font-semibold text-ctp-text">{value}</p></div>;
}

export default function CardInfoPanel({ card, illustrator, cardStat, metaShare, communityShare, quantityBuckets, resolveReference }: { card: Card; illustrator?: string | null; cardStat?: CardStat; metaShare: number | null; communityShare?: number; quantityBuckets: CardQuantityBucket[]; resolveReference: (reference: { slug: string; name: string }) => Card | undefined }) {
  return <>
    {cardStat && <Section className="mt-4" heading="dense" title="Tournament usage"><div className="grid grid-cols-2 gap-4 rounded-xl border border-ctp-surface1 bg-ctp-mantle p-4"><Metric label="Decks" value={cardStat.deckCount} /><Metric label="Adjusted win rate" value={`${(cardStat.adjustedWinRate * 100).toFixed(0)}%`} /></div><details className="mt-3 text-xs text-ctp-subtext0"><summary className="cursor-pointer text-ctp-blue">More usage data</summary><div className="mt-3 flex flex-wrap gap-x-5 gap-y-1"><span>{cardStat.eventCount} events</span>{metaShare !== null && <span>{(metaShare * 100).toFixed(1)}% meta share</span>}<span>{(cardStat.avgWinRate * 100).toFixed(0)}% raw win rate</span>{communityShare !== undefined && <span>{(communityShare * 100).toFixed(0)}% community share</span>}{cardStat.recentDeckCount > cardStat.priorDeckCount && cardStat.priorDeckCount > 0 && <span>Trending up</span>}</div></details></Section>}
    {quantityBuckets.length >= 2 && <Section className="mt-4" heading="dense" collapsible defaultOpen={false} title="Win rate by quantity" description="Does running more (or fewer) copies actually change the outcome?"><div className="mt-1 flex flex-wrap gap-4 text-sm text-ctp-subtext1">{quantityBuckets.map((bucket) => <span key={bucket.quantity}>{bucket.quantity}x: <span className="font-semibold text-ctp-text">{(bucket.adjustedWinRate * 100).toFixed(0)}%</span> <span className="text-xs text-ctp-subtext0">({bucket.deckCount} decks)</span></span>)}</div></Section>}
    {illustrator && <Section className="mt-4" heading="dense" collapsible defaultOpen={false} title="Illustrator"><Link to={`/cards?artist=${encodeURIComponent(illustrator)}`} className="mt-1 inline-block text-sm text-ctp-blue hover:underline">{illustrator}</Link></Section>}
    <Section className="mt-4" heading="dense" title="Legality"><div className="mt-1 flex flex-wrap gap-2 text-sm">{(["STANDARD", "PANTHEON"] as const).map((format) => { const limit = card.legality?.[format]?.limit; const inferred = limit === undefined; const effectiveLimit = limit ?? (format === "PANTHEON" ? 1 : 4); return <span key={format} className="text-ctp-subtext1">{format}: {effectiveLimit === 0 ? <span className="text-ctp-red">Banned</span> : <>Max {effectiveLimit}{inferred && <span className="text-ctp-subtext0"> (assumed)</span>}</>}</span>; })}</div></Section>
    {(card.references.length > 0 || card.referenced_by.length > 0) && <div className="mt-4 space-y-2">
      {card.references.length > 0 && <Section heading="dense" collapsible defaultOpen={false} title="References"><div className="mt-1 flex flex-wrap gap-2 text-sm">{card.references.map((reference) => <CardHoverPreview key={reference.slug} image={resolveReference(reference)?.editions[0]?.image} alt={reference.name}><Link to={`/cards/${reference.slug}`} className="text-ctp-blue hover:underline">{reference.name} <span className="text-ctp-subtext0">({reference.kind.toLowerCase()})</span></Link></CardHoverPreview>)}</div></Section>}
      {card.referenced_by.length > 0 && <Section heading="dense" collapsible defaultOpen={false} title="Referenced by"><div className="mt-1 flex flex-wrap gap-2 text-sm">{card.referenced_by.map((reference) => <CardHoverPreview key={reference.slug} image={resolveReference(reference)?.editions[0]?.image} alt={reference.name}><Link to={`/cards/${reference.slug}`} className="text-ctp-blue hover:underline">{reference.name}</Link></CardHoverPreview>)}</div></Section>}
    </div>}
  </>;
}
