import type { Card, CardQuantityBucket, CardStat } from "@gatcg/shared";
import { Link } from "react-router-dom";
import CardHoverPreview from "../../components/CardHoverPreview";
import Section from "../../components/ui/Section";

function Metric({ label, value, detail, tone = "default" }: { label: string; value: string | number; detail: string; tone?: "default" | "success" }) {
  return <div className={`rounded-xl p-4 ${tone === "success" ? "bg-ctp-green/10" : "bg-ctp-surface0"}`}><p className="text-[11px] font-semibold uppercase tracking-wide text-ctp-subtext0">{label}</p><p className={`mt-1 text-2xl font-bold ${tone === "success" ? "text-ctp-green" : "text-ctp-text"}`}>{value}</p><p className="mt-0.5 text-xs text-ctp-subtext0">{detail}</p></div>;
}

export default function CardInfoPanel({ card, illustrator, cardStat, metaShare, communityShare, quantityBuckets, resolveReference }: { card: Card; illustrator?: string | null; cardStat?: CardStat; metaShare: number | null; communityShare?: number; quantityBuckets: CardQuantityBucket[]; resolveReference: (reference: { slug: string; name: string }) => Card | undefined }) {
  return <>
    {cardStat && <Section className="mt-4" heading="dense" title="Tournament usage"><div className="grid grid-cols-2 gap-2 sm:grid-cols-3 lg:grid-cols-5"><Metric label="Decks" value={cardStat.deckCount} detail="Tournament lists" />{metaShare !== null && <Metric label="Meta share" value={`${(metaShare * 100).toFixed(1)}%`} detail="Tracked tournament decks" />}<Metric label="Events" value={cardStat.eventCount} detail="Distinct events" /><Metric label="Win rate" value={`${(cardStat.avgWinRate * 100).toFixed(0)}%`} detail="Raw results" /><Metric label="Adjusted" value={`${(cardStat.adjustedWinRate * 100).toFixed(0)}%`} detail="Strength-adjusted" tone={cardStat.adjustedWinRate >= 0.5 ? "success" : "default"} /></div>{cardStat.recentDeckCount > cardStat.priorDeckCount && cardStat.priorDeckCount > 0 && <p className="mt-2 inline-flex rounded-full bg-ctp-green/10 px-2.5 py-1 text-xs font-medium text-ctp-green">↗ Trending up</p>}{communityShare !== undefined && <p className="mt-1 text-xs text-ctp-mauve">{(communityShare * 100).toFixed(0)}% of community decks include this — popularity in community brews, not a performance figure like the stats above.</p>}</Section>}
    {quantityBuckets.length >= 2 && <Section className="mt-4" heading="dense" collapsible defaultOpen={false} title="Win rate by quantity" description="Does running more (or fewer) copies actually change the outcome?"><div className="mt-1 flex flex-wrap gap-4 text-sm text-ctp-subtext1">{quantityBuckets.map((bucket) => <span key={bucket.quantity}>{bucket.quantity}x: <span className="font-semibold text-ctp-text">{(bucket.adjustedWinRate * 100).toFixed(0)}%</span> <span className="text-xs text-ctp-subtext0">({bucket.deckCount} decks)</span></span>)}</div></Section>}
    {illustrator && <Section className="mt-4" heading="dense" collapsible defaultOpen={false} title="Illustrator"><Link to={`/cards?artist=${encodeURIComponent(illustrator)}`} className="mt-1 inline-block text-sm text-ctp-blue hover:underline">{illustrator}</Link></Section>}
    <Section className="mt-4" heading="dense" title="Legality"><div className="mt-1 flex flex-wrap gap-2 text-sm">{(["STANDARD", "PANTHEON"] as const).map((format) => { const limit = card.legality?.[format]?.limit; const inferred = limit === undefined; const effectiveLimit = limit ?? (format === "PANTHEON" ? 1 : 4); return <span key={format} className="text-ctp-subtext1">{format}: {effectiveLimit === 0 ? <span className="text-ctp-red">Banned</span> : <>Max {effectiveLimit}{inferred && <span className="text-ctp-subtext0"> (assumed)</span>}</>}</span>; })}</div></Section>
    {(card.references.length > 0 || card.referenced_by.length > 0) && <div className="mt-4 space-y-2">
      {card.references.length > 0 && <Section heading="dense" collapsible defaultOpen={false} title="References"><div className="mt-1 flex flex-wrap gap-2 text-sm">{card.references.map((reference) => <CardHoverPreview key={reference.slug} image={resolveReference(reference)?.editions[0]?.image} alt={reference.name}><Link to={`/cards/${reference.slug}`} className="text-ctp-blue hover:underline">{reference.name} <span className="text-ctp-subtext0">({reference.kind.toLowerCase()})</span></Link></CardHoverPreview>)}</div></Section>}
      {card.referenced_by.length > 0 && <Section heading="dense" collapsible defaultOpen={false} title="Referenced by"><div className="mt-1 flex flex-wrap gap-2 text-sm">{card.referenced_by.map((reference) => <CardHoverPreview key={reference.slug} image={resolveReference(reference)?.editions[0]?.image} alt={reference.name}><Link to={`/cards/${reference.slug}`} className="text-ctp-blue hover:underline">{reference.name}</Link></CardHoverPreview>)}</div></Section>}
    </div>}
  </>;
}
