import { useMemo, useState } from "react";
import { Link } from "react-router-dom";
import PageLayout from "../../components/layout/PageLayout";
import PageHeader from "../../components/ui/PageHeader";
import Panel from "../../components/ui/Panel";
import { useDocumentTitle } from "../../lib/useDocumentTitle";
import { addImportedMatches, loadMatchLog, previewClarentImport, type ClarentImportPreview, type MatchLogRecord, type MatchOrder, type MatchResult } from "../../lib/matchLog";
import { useCardCatalog } from "../cards/useCardCatalog";

const STORAGE_KEY = "fanofin:match-log:v1";
const readRecords = () => { try { return loadMatchLog(localStorage.getItem(STORAGE_KEY)); } catch { return []; } };
const splitList = (value: string) => value.split(",").map((item) => item.trim()).filter(Boolean);

export default function MatchLogIndex() {
  useDocumentTitle("Match Log", "Record manual games and preview Clarent simulator imports with their evidence source preserved.");
  const catalog = useCardCatalog();
  const knownCardIds = useMemo(() => new Set(catalog.map((card) => card.uuid)), [catalog]);
  const cardsByName = useMemo(() => new Map(catalog.map((card) => [card.name.toLowerCase(), card])), [catalog]);
  const [records, setRecordsState] = useState<MatchLogRecord[]>(readRecords);
  const [result, setResult] = useState<MatchResult>("win"); const [order, setOrder] = useState<MatchOrder>("first");
  const [opponent, setOpponent] = useState(""); const [deckLabel, setDeckLabel] = useState(""); const [turns, setTurns] = useState(""); const [mulligans, setMulligans] = useState("");
  const [sideboardPlan, setSideboardPlan] = useState(""); const [gamePlanTurn, setGamePlanTurn] = useState(""); const [notableCards, setNotableCards] = useState(""); const [bottlenecks, setBottlenecks] = useState(""); const [notes, setNotes] = useState("");
  const [importText, setImportText] = useState(""); const [playerSeat, setPlayerSeat] = useState<1 | 2>(1); const [preview, setPreview] = useState<{ previews: ClarentImportPreview[]; errors: string[] } | null>(null);
  const save = (next: MatchLogRecord[]) => { setRecordsState(next); try { localStorage.setItem(STORAGE_KEY, JSON.stringify(next)); } catch { /* Best effort. */ } };
  const wins = records.filter((record) => record.result === "win").length;
  const matchPoints = records.reduce((total, record) => total + (record.result === "win" ? 1 : record.result === "draw" ? 0.5 : 0), 0);

  function addManual() {
    const now = new Date().toISOString();
    const record: MatchLogRecord = { version: 1, id: crypto.randomUUID(), playedAt: now, result, order, turns: turns ? Math.max(0, Math.floor(Number(turns))) : null, mulligans: mulligans ? Math.max(0, Math.floor(Number(mulligans))) : null, opponent: opponent.trim(), deckLabel: deckLabel.trim(), sideboardPlan: sideboardPlan.trim(), gamePlanTurn: gamePlanTurn ? Math.max(1, Math.floor(Number(gamePlanTurn))) : null, notableCards: splitList(notableCards), bottlenecks: splitList(bottlenecks), notes: notes.trim(), provenance: { kind: "manual", enteredAt: now } };
    save([record, ...records]); setOpponent(""); setTurns(""); setMulligans(""); setSideboardPlan(""); setGamePlanTurn(""); setNotableCards(""); setBottlenecks(""); setNotes("");
  }

  return <PageLayout data-component="MatchLogIndex">
    <PageHeader title="Match Log" description="Keep self-recorded testing separate from tournament results, with the source of every game attached." />
    <div className="mt-4 grid grid-cols-3 gap-2"><Metric label="Games" value={`${records.length}`} /><Metric label="Wins" value={`${wins}`} /><Metric label="Match points" value={records.length ? `${Math.round(matchPoints / records.length * 100)}%` : "—"} /></div>
    <Panel className="mt-4"><h2 className="text-base font-semibold text-ctp-text">Log a game</h2><p className="mt-1 text-xs text-ctp-subtext0">Only result and play order are required. Add testing context when it will help explain the outcome later.</p>
      <div className="mt-3 grid gap-3 sm:grid-cols-2"><Select label="Result" value={result} onChange={(value) => setResult(value as MatchResult)} options={[["win","Win"],["loss","Loss"],["draw","Draw"]]} /><Select label="Play order" value={order} onChange={(value) => setOrder(value as MatchOrder)} options={[["first","Going first"],["second","Going second"],["unknown","Unknown"]]} /><Field label="Your deck or Champion" value={deckLabel} setValue={setDeckLabel} placeholder="Optional" /><Field label="Opponent, deck, or archetype" value={opponent} setValue={setOpponent} placeholder="Optional" /></div>
      <details className="mt-3 rounded-lg border border-ctp-surface1 p-3"><summary className="flex min-h-11 cursor-pointer list-none items-center text-sm font-medium text-ctp-blue [&::-webkit-details-marker]:hidden">Add game details</summary><div className="mt-2 grid gap-3 sm:grid-cols-2"><Field label="Turns" value={turns} setValue={setTurns} type="number" /><Field label="Mulligans" value={mulligans} setValue={setMulligans} type="number" /><Field label="Game plan online turn" value={gamePlanTurn} setValue={setGamePlanTurn} type="number" /><Field label="Notable cards" value={notableCards} setValue={setNotableCards} placeholder="Comma-separated card names" /><Field label="Bottlenecks" value={bottlenecks} setValue={setBottlenecks} placeholder="Resources, setup, interaction…" /><Field label="Sideboard plan" value={sideboardPlan} setValue={setSideboardPlan} placeholder="What came in or out?" /><label className="text-xs text-ctp-subtext0 sm:col-span-2">Notes<textarea value={notes} onChange={(event) => setNotes(event.target.value)} rows={3} className="mt-1 block w-full rounded-lg border border-ctp-surface1 bg-ctp-base px-3 py-2 text-sm text-ctp-text" /></label></div></details>
      <button type="button" onClick={addManual} className="mt-3 min-h-11 w-full rounded-lg bg-ctp-blue px-4 text-sm font-semibold text-ctp-base sm:w-auto">Add manual game</button>
    </Panel>
    <details className="mt-4 rounded-xl border border-ctp-surface1 bg-ctp-mantle p-3"><summary className="flex min-h-11 cursor-pointer list-none items-center justify-between gap-3 font-semibold text-ctp-text [&::-webkit-details-marker]:hidden"><span>Import from Clarent</span><span className="text-xs font-normal text-ctp-mauve">JSON preview</span></summary><p className="mt-2 text-xs leading-5 text-ctp-subtext1">Paste one Clarent/TCGEngine v1 game submission or an array. This is a local file/text import, not a live Clarent connection. Choose which seat was yours before previewing.</p><Select label="My seat" value={`${playerSeat}`} onChange={(value) => setPlayerSeat(value === "2" ? 2 : 1)} options={[["1","Player 1"],["2","Player 2"]]} /><textarea value={importText} onChange={(event) => setImportText(event.target.value)} rows={7} placeholder="Paste Clarent submission JSON" className="mt-3 block w-full rounded-lg border border-ctp-surface1 bg-ctp-base p-3 font-mono text-xs text-ctp-text"/><button type="button" disabled={!importText.trim()} onClick={() => setPreview(previewClarentImport(importText, playerSeat, records, knownCardIds))} className="mt-3 min-h-11 w-full rounded-lg border border-ctp-mauve/60 px-4 text-sm font-semibold text-ctp-mauve disabled:opacity-40 sm:w-auto">Preview import</button>{preview && <ImportPreview value={preview} onImport={() => { save(addImportedMatches(records, preview.previews)); setPreview(null); setImportText(""); }} />}</details>
    <section className="mt-6"><h2 className="text-base font-semibold text-ctp-text">Recent games</h2>{records.length === 0 ? <p className="mt-3 rounded-xl border border-dashed border-ctp-surface1 p-6 text-center text-sm text-ctp-subtext0">No games logged yet.</p> : <div className="mt-3 space-y-3">{records.map((record) => <article key={record.id} className="rounded-xl border border-ctp-surface1 bg-ctp-mantle p-3"><div className="flex items-start justify-between gap-3"><div><p className="font-semibold text-ctp-text">{record.deckLabel || "Unspecified deck"} <span className="font-normal text-ctp-subtext0">vs.</span> {record.opponent || "unspecified opponent"}</p><p className="mt-1 text-xs text-ctp-subtext0">{new Date(record.playedAt).toLocaleDateString()} · {record.order === "first" ? "First" : record.order === "second" ? "Second" : "Order unknown"}{record.turns != null ? ` · ${record.turns} turns` : ""}</p></div><span className={`rounded-full px-2 py-1 text-[10px] font-bold uppercase ${record.result === "win" ? "bg-ctp-green/10 text-ctp-green" : record.result === "loss" ? "bg-ctp-red/10 text-ctp-red" : "bg-ctp-yellow/10 text-ctp-yellow"}`}>{record.result}</span></div>{record.notableCards.length > 0 && <div className="mt-3 flex flex-wrap gap-2">{record.notableCards.map((name) => { const card = cardsByName.get(name.toLowerCase()); return card ? <Link key={name} to={`/cards/${card.slug}`} className="rounded-full bg-ctp-blue/10 px-2 py-1 text-xs text-ctp-blue">{card.name}</Link> : <span key={name} className="rounded-full bg-ctp-surface0 px-2 py-1 text-xs text-ctp-subtext1">{name}</span>; })}</div>}<details className="mt-2"><summary className="cursor-pointer text-xs text-ctp-blue">Details and source</summary><div className="mt-2 space-y-1 text-xs text-ctp-subtext1">{record.sideboardPlan && <p>Sideboard: {record.sideboardPlan}</p>}{record.bottlenecks.length > 0 && <p>Bottlenecks: {record.bottlenecks.join(", ")}</p>}{record.notes && <p>{record.notes}</p>}<p className="text-ctp-subtext0">Source: {record.provenance.kind === "manual" ? "Manual entry" : `Clarent ${record.provenance.submissionId} · imported ${new Date(record.provenance.importedAt).toLocaleString()}`}</p></div></details><button type="button" onClick={() => save(records.filter((item) => item.id !== record.id))} className="mt-3 min-h-11 text-xs text-ctp-red">Remove</button></article>)}</div>}</section>
    <p className="mt-4 text-xs leading-5 text-ctp-subtext0">This is descriptive self-recorded evidence. Small samples, opponent selection, familiarity, and incomplete logging can strongly bias it; it is never blended into tournament win rates.</p>
  </PageLayout>;
}

function ImportPreview({ value, onImport }: { value: { previews: ClarentImportPreview[]; errors: string[] }; onImport: () => void }) { const fresh = value.previews.filter((entry) => !entry.duplicate); return <div className="mt-3 rounded-lg border border-ctp-surface1 bg-ctp-base p-3"><h3 className="text-sm font-semibold text-ctp-text">Import preview</h3>{value.errors.map((error) => <p key={error} className="mt-2 text-xs text-ctp-red">{error}</p>)}<div className="mt-2 space-y-2">{value.previews.map((entry) => <div key={entry.record.id} className="rounded-lg border border-ctp-surface1 p-2 text-xs"><p className="font-medium text-ctp-text">{entry.record.deckLabel} vs. {entry.record.opponent} · {entry.record.result}</p><p className="mt-1 text-ctp-subtext0">{entry.duplicate ? "Already imported — will be skipped" : "Ready to import"} · {entry.record.provenance.kind === "clarent" ? entry.record.provenance.submissionId : ""}</p>{entry.unresolvedCardIds.length > 0 && <details className="mt-2"><summary className="cursor-pointer text-ctp-yellow">{entry.unresolvedCardIds.length} unresolved card ID{entry.unresolvedCardIds.length === 1 ? "" : "s"}</summary><p className="mt-1 break-all text-ctp-subtext0">{entry.unresolvedCardIds.join(", ")}</p></details>}</div>)}</div><button type="button" disabled={fresh.length === 0} onClick={onImport} className="mt-3 min-h-11 w-full rounded-lg bg-ctp-mauve px-4 text-sm font-semibold text-ctp-base disabled:opacity-40 sm:w-auto">Import {fresh.length} new game{fresh.length === 1 ? "" : "s"}</button></div>; }
function Field({ label, value, setValue, placeholder, type = "text" }: { label: string; value: string; setValue: (value: string) => void; placeholder?: string; type?: string }) { return <label className="text-xs text-ctp-subtext0">{label}<input type={type} min={type === "number" ? 0 : undefined} value={value} onChange={(event) => setValue(event.target.value)} placeholder={placeholder} className="mt-1 block min-h-11 w-full rounded-lg border border-ctp-surface1 bg-ctp-base px-3 text-sm text-ctp-text" /></label>; }
function Select({ label, value, onChange, options }: { label: string; value: string; onChange: (value: string) => void; options: [string,string][] }) { return <label className="mt-3 block text-xs text-ctp-subtext0">{label}<select value={value} onChange={(event) => onChange(event.target.value)} className="mt-1 block min-h-11 w-full rounded-lg border border-ctp-surface1 bg-ctp-base px-3 text-sm text-ctp-text sm:max-w-xs">{options.map(([key, text]) => <option key={key} value={key}>{text}</option>)}</select></label>; }
function Metric({ label, value }: { label: string; value: string }) { return <div className="rounded-xl border border-ctp-surface1 bg-ctp-mantle p-3"><p className="text-[10px] uppercase tracking-wide text-ctp-subtext0">{label}</p><p className="mt-1 text-xl font-bold tabular-nums text-ctp-text">{value}</p></div>; }
