import { useMemo, useState } from "react";
import type { Card } from "@gatcg/shared";
import { computeEngineBalance } from "../../lib/engineBalance";
import type { GamePlanRole } from "../../lib/gamePlanReadiness";
import { inferStartingHandSize, type PlayOrder } from "../../lib/turnToPlay";

interface Line { name: string; quantity: number }
type Role = "producer" | "payoff";
const percent = (value: number) => `${(value * 100).toFixed(1)}%`;

export default function EnginePayoffBalance({ mainLines, materialLines, catalogByName, sharedAssignments, onSharedAssignmentsChange }: { mainLines: Line[]; materialLines: Line[]; catalogByName: Map<string, Card>; sharedAssignments?: Record<string, GamePlanRole | "">; onSharedAssignmentsChange?: (assignments: Record<string, GamePlanRole | "">) => void }) {
  const [localAssignments, setLocalAssignments] = useState<Record<string, Role | "">>({});
  const assignments: Record<string, Role | ""> = sharedAssignments ? Object.fromEntries(Object.entries(sharedAssignments).map(([name, role]) => [name, role === "enabler" ? "producer" : role === "payoff" ? "payoff" : ""])) : localAssignments;
  const updateAssignment = (name: string, role: Role | "") => {
    if (sharedAssignments && onSharedAssignmentsChange) onSharedAssignmentsChange({ ...sharedAssignments, [name]: role === "producer" ? "enabler" : role });
    else setLocalAssignments((current) => ({ ...current, [name]: role }));
  };
  const clearAssignments = () => sharedAssignments && onSharedAssignmentsChange ? onSharedAssignmentsChange({}) : setLocalAssignments({});
  const [producerRequired, setProducerRequired] = useState(1);
  const [payoffRequired, setPayoffRequired] = useState(1);
  const [setupTurn, setSetupTurn] = useState(2);
  const [payoffTurn, setPayoffTurn] = useState(4);
  const [playOrder, setPlayOrder] = useState<PlayOrder>("first");
  const [query, setQuery] = useState("");
  const producers = mainLines.filter((line) => assignments[line.name] === "producer");
  const payoffs = mainLines.filter((line) => assignments[line.name] === "payoff");
  const producerCopies = producers.reduce((sum, line) => sum + line.quantity, 0);
  const payoffCopies = payoffs.reduce((sum, line) => sum + line.quantity, 0);
  const deckSize = mainLines.reduce((sum, line) => sum + line.quantity, 0);
  const opening = inferStartingHandSize(materialLines, catalogByName);
  const result = computeEngineBalance(deckSize, opening, { producerCopies, producerRequired, payoffCopies, payoffRequired }, setupTurn, payoffTurn, playOrder);
  const filtered = useMemo(() => mainLines.filter((line) => line.name.toLowerCase().includes(query.trim().toLowerCase())), [mainLines, query]);
  const ready = producers.length > 0 && payoffs.length > 0;

  return <section data-component="EnginePayoffBalance" className="pt-3">
    <div className="flex flex-wrap items-start justify-between gap-3"><div><h3 className="font-semibold text-ctp-text">Setup-to-Payoff Timing</h3><p className="mt-1 max-w-2xl text-xs text-ctp-subtext0">Test a staged plan: setup must be found by the first deadline, then the payoff by a later deadline.</p>{sharedAssignments && <p className="mt-1 text-[10px] font-medium text-ctp-blue">Setup and Payoff come from the shared Prepare Analysis profile.</p>}</div><button type="button" onClick={clearAssignments} disabled={!Object.values(assignments).some(Boolean)} className="min-h-11 rounded-lg px-3 text-xs text-ctp-subtext1 hover:bg-ctp-surface0 disabled:opacity-40">Clear roles</button></div>
    <div className="mt-3 rounded-lg border border-ctp-surface1 bg-ctp-base/35 p-3 text-xs leading-5 text-ctp-subtext1"><strong className="text-ctp-text">How this differs:</strong> Game Plan Readiness checks every selected role at one turn. This view answers whether setup arrives early enough before a later payoff and shows which half is stranded.</div>
    <div className="mt-4 grid gap-3 lg:grid-cols-[minmax(0,1.2fr)_minmax(18rem,0.8fr)]"><div><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Filter cards…" aria-label="Filter engine cards" className="w-full rounded-md border border-ctp-surface1 bg-ctp-base px-3 py-2 text-sm text-ctp-text" /><div className="mt-2 max-h-80 overflow-y-auto rounded-lg border border-ctp-surface1">{filtered.map((line) => <div key={line.name} className="grid grid-cols-[minmax(0,1fr)_8.5rem] items-center gap-2 border-b border-ctp-surface0 px-3 py-2 last:border-0"><div className="min-w-0"><p className="truncate text-sm text-ctp-text">{line.name}</p><p className="text-[10px] text-ctp-subtext0">{line.quantity} copies</p></div><select value={assignments[line.name] ?? ""} onChange={(event) => updateAssignment(line.name, event.target.value as Role | "")} aria-label={`Engine role for ${line.name}`} className="rounded-md border border-ctp-surface1 bg-ctp-mantle px-2 py-1.5 text-xs text-ctp-text"><option value="">Unassigned</option><option value="producer">Producer</option><option value="payoff">Payoff</option></select></div>)}</div></div>
      <div className="space-y-3"><div className="grid grid-cols-2 gap-2"><RoleCard label="Producers" copies={producerCopies} required={producerRequired} onRequired={setProducerRequired} /><RoleCard label="Payoffs" copies={payoffCopies} required={payoffRequired} onRequired={setPayoffRequired} /></div><div className="grid grid-cols-3 gap-2"><TurnControl label="Setup by" value={setupTurn} onChange={(value) => { setSetupTurn(value); setPayoffTurn((current) => Math.max(current, value)); }} /><TurnControl label="Payoff by" value={payoffTurn} onChange={(value) => setPayoffTurn(Math.max(setupTurn, value))} /><label className="text-xs text-ctp-subtext0">Order<select value={playOrder} onChange={(event) => setPlayOrder(event.target.value as PlayOrder)} className="mt-1 block w-full rounded-md border border-ctp-surface1 bg-ctp-base px-2 py-2 text-sm text-ctp-text"><option value="first">First</option><option value="second">Second</option></select></label></div>{!ready ? <div className="rounded-lg border border-ctp-blue/30 bg-ctp-blue/5 p-3 text-sm text-ctp-subtext1">Assign at least one Producer and one Payoff.</div> : <><div className="grid grid-cols-2 gap-2"><Metric label="Engine online" value={percent(result.onlineProbability)} /><Metric label="Payoff given setup" value={percent(result.payoffGivenSetup)} /><Metric label="Stranded payoff" value={percent(result.payoffStrandedProbability)} /><Metric label="Unused setup" value={percent(result.setupUnusedProbability)} /></div><div className="rounded-lg border border-ctp-surface1 bg-ctp-base/35 p-3 text-xs text-ctp-subtext1"><p><b className="text-ctp-text">Ratio bottleneck:</b> {result.bottleneck === "producer" ? "Producer access" : result.bottleneck === "payoff" ? "Payoff access" : "Balanced at this checkpoint"}</p>{result.bestAdditionalCopy && <p className="mt-2 text-ctp-green">Best extra role copy: {result.bestAdditionalCopy.role === "producer" ? "Producer" : "Payoff"} (+{(result.bestAdditionalCopy.gain * 100).toFixed(1)} points)</p>}</div></>}</div></div>
    {ready && <div className="mt-4 grid gap-2 sm:grid-cols-2 lg:grid-cols-4">{result.points.map((point) => <div key={point.turn} className="rounded-lg border border-ctp-surface1 bg-ctp-base/35 p-3"><div className="flex justify-between gap-2"><span className="font-semibold text-ctp-text">Payoff T{point.turn}</span><span className="font-bold tabular-nums text-ctp-mauve">{percent(point.onlineProbability)}</span></div><p className="mt-1 text-[10px] text-ctp-subtext0">Setup deadline T{setupTurn} · {point.payoffSeen} cards seen by payoff</p></div>)}</div>}
    <p className="mt-3 text-[11px] leading-4 text-ctp-subtext0">Exact deadline-based access odds for disjoint pools. “Online” means the selected quantities were found by their deadlines; activation, costs, board state, and whether the chosen cards truly work together are not modeled.</p>
  </section>;
}

function RoleCard({ label, copies, required, onRequired }: { label: string; copies: number; required: number; onRequired: (value: number) => void }) { return <label className="rounded-lg border border-ctp-surface1 bg-ctp-base/40 p-3 text-xs"><span className="font-semibold text-ctp-text">{label}</span><span className="mt-1 block text-xl font-bold tabular-nums text-ctp-text">{copies}</span><span className="mt-1 flex items-center gap-1 text-[10px] text-ctp-subtext0">Need <select value={required} onChange={(event) => onRequired(Number(event.target.value))} className="rounded border border-ctp-surface1 bg-ctp-mantle px-1">{[1,2,3,4].map((value) => <option key={value}>{value}</option>)}</select></span></label>; }
function TurnControl({ label, value, onChange }: { label: string; value: number; onChange: (value: number) => void }) { return <label className="text-xs text-ctp-subtext0">{label}<select value={value} onChange={(event) => onChange(Number(event.target.value))} className="mt-1 block w-full rounded-md border border-ctp-surface1 bg-ctp-base px-2 py-2 text-sm text-ctp-text">{[1,2,3,4,5,6,7,8].map((turn) => <option key={turn} value={turn}>T{turn}</option>)}</select></label>; }
function Metric({ label, value }: { label: string; value: string }) { return <div className="rounded-lg border border-ctp-surface1 bg-ctp-base/40 p-2"><p className="text-[9px] uppercase tracking-wide text-ctp-subtext0">{label}</p><p className="mt-1 text-lg font-bold tabular-nums text-ctp-text">{value}</p></div>; }
