import { useMemo, useState } from "react";
import type { Card } from "@gatcg/shared";
import CardImage from "../../components/CardImage";
import { computeHandRecipe } from "../../lib/functionalHand";
import type { GamePlanRole } from "../../lib/gamePlanReadiness";
import { inferStartingHandSize, type PlayOrder } from "../../lib/turnToPlay";

interface Line { name: string; quantity: number }
interface RecipeGroup { id: string; label: string; minimum: number }
const STARTING_GROUPS: RecipeGroup[] = [{ id: "early", label: "Early action", minimum: 1 }, { id: "setup", label: "Setup piece", minimum: 1 }];

export default function FunctionalHandCalculator({ mainLines, materialLines, catalogByName, sharedAssignments }: { mainLines: Line[]; materialLines: Line[]; catalogByName: Map<string, Card>; sharedAssignments?: Record<string, GamePlanRole | ""> }) {
  const [groups, setGroups] = useState<RecipeGroup[]>(STARTING_GROUPS);
  const [assignments, setAssignments] = useState<Record<string, string>>({});
  const [maximumUnwanted, setMaximumUnwanted] = useState(1);
  const [targetTurn, setTargetTurn] = useState(3);
  const [playOrder, setPlayOrder] = useState<PlayOrder>("first");
  const [query, setQuery] = useState("");
  const deckSize = mainLines.reduce((sum, line) => sum + line.quantity, 0);
  const opening = inferStartingHandSize(materialLines, catalogByName);
  const recipeGroups = groups.map((group) => ({ ...group, copies: mainLines.filter((line) => assignments[line.name] === group.id).reduce((sum, line) => sum + line.quantity, 0) }));
  const unwantedCopies = mainLines.filter((line) => assignments[line.name] === "unwanted").reduce((sum, line) => sum + line.quantity, 0);
  const result = computeHandRecipe(deckSize, opening, recipeGroups, unwantedCopies, maximumUnwanted, targetTurn, playOrder);
  const filtered = useMemo(() => mainLines.filter((line) => line.name.toLocaleLowerCase("en-US").includes(query.trim().toLocaleLowerCase("en-US"))), [mainLines, query]);
  const canCalculate = recipeGroups.length > 0 && recipeGroups.every((group) => group.copies >= group.minimum);
  const canSeedFromPlan = sharedAssignments && Object.values(sharedAssignments).some((role) => role === "enabler" || role === "protection");
  const percent = (value: number) => `${(value * 100).toFixed(1)}%`;

  function addGroup() { const id = `group-${Date.now()}`; setGroups((current) => [...current, { id, label: `Requirement ${current.length + 1}`, minimum: 1 }]); }
  function removeGroup(id: string) { setGroups((current) => current.filter((group) => group.id !== id)); setAssignments((current) => Object.fromEntries(Object.entries(current).map(([name, value]) => [name, value === id ? "" : value]))); }
  function seedFromPlan() {
    if (!sharedAssignments) return;
    const seeded: RecipeGroup[] = [];
    if (Object.values(sharedAssignments).includes("enabler")) seeded.push({ id: "setup", label: "Setup piece", minimum: 1 });
    if (Object.values(sharedAssignments).includes("protection")) seeded.push({ id: "protection", label: "Protection", minimum: 1 });
    setGroups(seeded);
    setAssignments(Object.fromEntries(mainLines.map((line) => [line.name, sharedAssignments[line.name] === "enabler" ? "setup" : sharedAssignments[line.name] === "protection" ? "protection" : ""])));
  }

  return <section data-component="FunctionalHandCalculator" className="pt-3">
    <div className="flex flex-col gap-3 sm:flex-row sm:items-start sm:justify-between"><div><h3 className="font-semibold text-ctp-text">Opening Hand Recipe</h3><p className="mt-1 max-w-2xl text-xs text-ctp-subtext0">Name the ingredients this deck needs early. Multiple cards in one requirement are alternatives: drawing any of them counts. Cards in another plan stay neutral unless you explicitly mark them “Avoid early.”</p></div><div className="flex flex-wrap gap-2">{canSeedFromPlan && <button type="button" onClick={seedFromPlan} className="min-h-11 rounded-lg px-3 text-xs font-medium text-ctp-blue hover:bg-ctp-blue/10">Use prepared plan</button>}<button type="button" onClick={() => setAssignments({})} disabled={!Object.values(assignments).some(Boolean)} className="min-h-11 rounded-lg px-3 text-xs font-medium text-ctp-subtext1 hover:bg-ctp-surface0 disabled:opacity-40">Clear cards</button></div></div>
    <div className="mt-4 grid gap-4 lg:grid-cols-[minmax(0,1.15fr)_minmax(19rem,0.85fr)]">
      <div><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Filter cards…" aria-label="Filter opening hand cards" className="min-h-11 w-full rounded-lg border border-ctp-surface1 bg-ctp-base px-3 py-2 text-base text-ctp-text sm:text-sm" /><div className="mt-2 max-h-[32rem] overflow-y-auto rounded-xl border border-ctp-surface1 bg-ctp-base/30">{filtered.map((line) => { const card = catalogByName.get(line.name); return <div key={line.name} className="grid grid-cols-[3rem_minmax(0,1fr)] gap-3 border-b border-ctp-surface0 p-3 last:border-0 sm:grid-cols-[3rem_minmax(0,1fr)_11rem] sm:items-center">{card?.editions[0] ? <CardImage image={card.editions[0].image} alt={line.name} className="h-[4.2rem] w-12 rounded-md object-cover object-top" /> : <div className="h-[4.2rem] w-12 rounded-md bg-ctp-surface0" />}<div className="min-w-0"><p className="truncate text-sm font-medium text-ctp-text">{line.name}</p><p className="text-[10px] text-ctp-subtext0">{line.quantity} copies</p></div><select value={assignments[line.name] ?? ""} onChange={(event) => setAssignments((current) => ({ ...current, [line.name]: event.target.value }))} aria-label={`Opening hand recipe assignment for ${line.name}`} className="col-span-2 min-h-11 rounded-lg border border-ctp-surface1 bg-ctp-mantle px-2 text-sm text-ctp-text sm:col-span-1"><option value="">Neutral for this recipe</option>{groups.map((group) => <option key={group.id} value={group.id}>{group.label}</option>)}<option value="unwanted">Avoid early</option></select></div>; })}</div></div>
      <div className="space-y-3"><div className="rounded-xl border border-ctp-surface1 bg-ctp-base/40 p-3"><div className="flex items-center justify-between gap-3"><div><h4 className="text-sm font-semibold text-ctp-text">Required ingredients</h4><p className="mt-0.5 text-[10px] text-ctp-subtext0">Every group is required; cards inside a group are alternatives.</p></div>{groups.length < 5 && <button type="button" onClick={addGroup} className="min-h-10 rounded-lg px-3 text-xs font-medium text-ctp-blue">+ Add</button>}</div><div className="mt-3 space-y-2">{groups.map((group) => { const copies = recipeGroups.find((item) => item.id === group.id)?.copies ?? 0; return <div key={group.id} className="rounded-lg border border-ctp-surface1 bg-ctp-mantle p-2"><div className="grid grid-cols-[minmax(0,1fr)_4.5rem_auto] gap-2"><label className="text-[10px] text-ctp-subtext0">Name<input value={group.label} onChange={(event) => setGroups((current) => current.map((item) => item.id === group.id ? { ...item, label: event.target.value } : item))} className="mt-1 min-h-10 w-full rounded-lg border border-ctp-surface1 bg-ctp-base px-2 text-sm text-ctp-text" /></label><label className="text-[10px] text-ctp-subtext0">Need<select value={group.minimum} onChange={(event) => setGroups((current) => current.map((item) => item.id === group.id ? { ...item, minimum: Number(event.target.value) } : item))} className="mt-1 min-h-10 w-full rounded-lg border border-ctp-surface1 bg-ctp-base px-2 text-sm text-ctp-text">{[1,2,3].map((value) => <option key={value}>{value}</option>)}</select></label><button type="button" aria-label={`Remove ${group.label}`} onClick={() => removeGroup(group.id)} className="mt-4 min-h-10 min-w-10 rounded-full text-ctp-red hover:bg-ctp-red/10">×</button></div><p className={`mt-2 text-xs ${copies >= group.minimum ? "text-ctp-green" : "text-ctp-yellow"}`}>{copies} assigned copies{copies < group.minimum ? ` · assign at least ${group.minimum}` : ""}</p></div>; })}{groups.length === 0 && <p className="rounded-lg bg-ctp-blue/5 p-3 text-xs text-ctp-subtext1">Add a requirement to define this recipe.</p>}</div></div>
        <div className="rounded-xl border border-ctp-surface1 bg-ctp-base/40 p-3"><div className="flex items-center justify-between gap-3"><div><h4 className="text-sm font-semibold text-ctp-text">Avoid early <span className="font-normal text-ctp-subtext0">(optional)</span></h4><p className="mt-0.5 text-[10px] text-ctp-subtext0">Only cards that actively make this opening worse.</p></div><span className="font-bold tabular-nums text-ctp-text">{unwantedCopies}</span></div><label className="mt-3 flex min-h-11 items-center justify-between gap-2 text-xs text-ctp-subtext1">Allow at most<select value={maximumUnwanted} onChange={(event) => setMaximumUnwanted(Number(event.target.value))} className="min-h-10 rounded-lg border border-ctp-surface1 bg-ctp-mantle px-3 text-sm text-ctp-text">{[0,1,2,3,4].map((value) => <option key={value}>{value}</option>)}</select></label></div>
        <div className="grid grid-cols-2 gap-2"><label className="text-xs text-ctp-subtext0">Target turn<select value={targetTurn} onChange={(event) => setTargetTurn(Number(event.target.value))} className="mt-1 min-h-11 w-full rounded-lg border border-ctp-surface1 bg-ctp-base px-2 text-sm text-ctp-text">{[1,2,3,4,5,6,7,8].map((turn) => <option key={turn} value={turn}>Turn {turn}</option>)}</select></label><label className="text-xs text-ctp-subtext0">Play order<select value={playOrder} onChange={(event) => setPlayOrder(event.target.value as PlayOrder)} className="mt-1 min-h-11 w-full rounded-lg border border-ctp-surface1 bg-ctp-base px-2 text-sm text-ctp-text"><option value="first">Going first</option><option value="second">Going second</option></select></label></div>
        {!canCalculate ? <div className="rounded-xl border border-ctp-blue/30 bg-ctp-blue/5 p-3 text-sm text-ctp-subtext1">Assign enough cards to every required ingredient. Alternatives belong in the same group.</div> : <><div className="grid grid-cols-3 gap-2"><Metric label="Opening" value={percent(result.openingProbability)} /><Metric label={`Turn ${targetTurn}`} value={percent(result.targetProbability)} /><Metric label="First 10" value={percent(result.firstTenProbability)} /></div><div className="rounded-xl border border-ctp-surface1 bg-ctp-base/40 p-3 text-xs text-ctp-subtext1"><p><b className="text-ctp-text">Least reliable ingredient:</b> {result.bottleneck?.label ?? "—"}</p>{result.bestAdditionalCopy && <p className="mt-2 text-ctp-green">Best extra copy: {result.bestAdditionalCopy.label} (+{(result.bestAdditionalCopy.gain * 100).toFixed(1)} points by turn {targetTurn})</p>}</div></>}
      </div>
    </div>
    {canCalculate && <details className="mt-4 rounded-xl border border-ctp-surface1"><summary className="flex min-h-11 cursor-pointer items-center px-3 text-xs font-medium text-ctp-blue">Turn-by-turn probability</summary><div className="overflow-x-auto border-t border-ctp-surface1"><table className="w-full min-w-[34rem] text-xs"><thead className="text-ctp-subtext0"><tr><th className="px-2 py-1.5 text-left">Turn</th>{result.points.map((point) => <th key={point.turn} className="px-2 py-1.5 text-right">{point.turn}</th>)}</tr></thead><tbody><tr className="border-t border-ctp-surface1"><th className="px-2 py-2 text-left font-medium text-ctp-text">Recipe complete</th>{result.points.map((point) => <td key={point.turn} className="px-2 py-2 text-right font-medium tabular-nums text-ctp-blue">{percent(point.probability)}</td>)}</tr><tr className="border-t border-ctp-surface0 text-ctp-subtext0"><th className="px-2 py-2 text-left font-medium">Cards seen</th>{result.points.map((point) => <td key={point.turn} className="px-2 py-2 text-right tabular-nums">{point.seen}</td>)}</tr></tbody></table></div></details>}
    <p className="mt-3 text-[11px] leading-4 text-ctp-subtext0">Exact multivariate hypergeometric odds without replacement. Requirement pools must be disjoint, so one physical card cannot satisfy two ingredients. The result measures access only—not legality, affordability, sequencing, or strategic compatibility.</p>
  </section>;
}

function Metric({ label, value }: { label: string; value: string }) { return <div className="rounded-xl border border-ctp-surface1 bg-ctp-base/40 p-2 text-center"><p className="text-[9px] uppercase tracking-wide text-ctp-subtext0">{label}</p><p className="mt-1 text-lg font-bold tabular-nums text-ctp-text">{value}</p></div>; }
