import { useMemo, useState } from "react";
import type { Card } from "@gatcg/shared";
import { computeInteractionCoverage } from "../../lib/interactionCoverage";
import { inferStartingHandSize, type PlayOrder } from "../../lib/turnToPlay";

interface Line { name: string; quantity: number }
interface Scenario { id: string; name: string; turn: number; answers: string[] }
const percent = (value: number) => `${(value * 100).toFixed(1)}%`;

export default function InteractionCoverageMatrix({ mainLines, materialLines, sideboardLines, catalogByName }: { mainLines: Line[]; materialLines: Line[]; sideboardLines: Line[]; catalogByName: Map<string, Card> }) {
  const [scenarios, setScenarios] = useState<Scenario[]>([{ id: "1", name: "Wide board", turn: 3, answers: [] }]);
  const [activeId, setActiveId] = useState("1");
  const [playOrder, setPlayOrder] = useState<PlayOrder>("first");
  const [query, setQuery] = useState("");
  const active = scenarios.find((scenario) => scenario.id === activeId) ?? scenarios[0];
  const deckSize = mainLines.reduce((sum, line) => sum + line.quantity, 0);
  const opening = inferStartingHandSize(materialLines, catalogByName);
  const allLines = useMemo(() => {
    const names = new Set([...mainLines, ...sideboardLines].map((line) => line.name));
    return [...names].map((name) => ({ name, main: mainLines.find((line) => line.name === name)?.quantity ?? 0, side: sideboardLines.find((line) => line.name === name)?.quantity ?? 0 })).filter((line) => line.name.toLowerCase().includes(query.trim().toLowerCase()));
  }, [mainLines, sideboardLines, query]);
  const rows = scenarios.map((scenario) => {
    const mainCopies = mainLines.filter((line) => scenario.answers.includes(line.name)).reduce((sum, line) => sum + line.quantity, 0);
    const sideCopies = sideboardLines.filter((line) => scenario.answers.includes(line.name)).reduce((sum, line) => sum + line.quantity, 0);
    return { scenario, result: computeInteractionCoverage(deckSize, opening, scenario.turn, playOrder, mainCopies, sideCopies) };
  });
  function update(id: string, change: Partial<Scenario>) { setScenarios((current) => current.map((scenario) => scenario.id === id ? { ...scenario, ...change } : scenario)); }
  function toggle(name: string) { if (!active) return; update(active.id, { answers: active.answers.includes(name) ? active.answers.filter((answer) => answer !== name) : [...active.answers, name] }); }
  function addScenario() { const id = crypto.randomUUID(); setScenarios((current) => [...current, { id, name: `Scenario ${current.length + 1}`, turn: 3, answers: [] }]); setActiveId(id); }

  return <section data-component="InteractionCoverageMatrix" className="pt-3">
    <div className="flex flex-wrap items-start justify-between gap-3"><div><h3 className="font-semibold text-ctp-text">Interaction Coverage Matrix</h3><p className="mt-1 max-w-2xl text-xs text-ctp-subtext0">Name the opposing plans you care about, choose cards that answer each one, and set the turn when that interaction needs to be available.</p></div><label className="text-xs text-ctp-subtext0">Play order<select value={playOrder} onChange={(event) => setPlayOrder(event.target.value as PlayOrder)} className="ml-2 rounded-md border border-ctp-surface1 bg-ctp-base px-2 py-1.5 text-ctp-text"><option value="first">Going first</option><option value="second">Going second</option></select></label></div>
    <div className="mt-4 flex gap-2 overflow-x-auto pb-1">{scenarios.map((scenario) => <button key={scenario.id} type="button" onClick={() => setActiveId(scenario.id)} className={`shrink-0 rounded-full px-3 py-1.5 text-xs font-medium ${scenario.id === activeId ? "bg-ctp-blue text-ctp-base" : "border border-ctp-surface1 text-ctp-subtext1"}`}>{scenario.name}</button>)}{scenarios.length < 4 && <button type="button" onClick={addScenario} className="shrink-0 rounded-full border border-dashed border-ctp-surface1 px-3 py-1.5 text-xs text-ctp-subtext0">+ Scenario</button>}</div>
    {active && <div className="mt-3 grid gap-3 lg:grid-cols-[minmax(0,1.2fr)_minmax(18rem,0.8fr)]"><div><div className="grid grid-cols-[1fr_7rem] gap-2"><input value={active.name} onChange={(event) => update(active.id, { name: event.target.value })} aria-label="Scenario name" className="rounded-md border border-ctp-surface1 bg-ctp-base px-3 py-2 text-sm text-ctp-text" /><label className="text-xs text-ctp-subtext0">Critical turn<select value={active.turn} onChange={(event) => update(active.id, { turn: Number(event.target.value) })} className="mt-1 block w-full rounded-md border border-ctp-surface1 bg-ctp-base px-2 py-1.5 text-sm text-ctp-text">{[1,2,3,4,5,6,7,8].map((turn) => <option key={turn} value={turn}>Turn {turn}</option>)}</select></label></div><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Filter possible answers…" aria-label="Filter possible answers" className="mt-2 w-full rounded-md border border-ctp-surface1 bg-ctp-base px-3 py-2 text-sm text-ctp-text" /><div className="mt-2 max-h-72 overflow-y-auto rounded-lg border border-ctp-surface1">{allLines.map((line) => <label key={line.name} className="flex cursor-pointer items-center gap-3 border-b border-ctp-surface0 px-3 py-2 last:border-0"><input type="checkbox" checked={active.answers.includes(line.name)} onChange={() => toggle(line.name)} /><span className="min-w-0 flex-1 truncate text-sm text-ctp-text">{line.name}</span><span className="text-[10px] text-ctp-subtext0">{line.main} main{line.side > 0 ? ` · ${line.side} side` : ""}</span></label>)}</div></div><div>{(() => { const row = rows.find((item) => item.scenario.id === active.id)!; return <div className="space-y-3"><div className="grid grid-cols-2 gap-2"><Metric label="Preboard access" value={percent(row.result.preboardProbability)} /><Metric label="Postboard access" value={percent(row.result.postboardProbability)} /><Metric label="Main answers" value={`${row.result.mainCopies}`} /><Metric label="Cards seen" value={`${row.result.seen}`} /></div>{row.result.gain > 0 && <p className="rounded-lg border border-ctp-green/30 bg-ctp-green/5 p-3 text-xs text-ctp-green">Selected Sideboard answers add {(row.result.gain * 100).toFixed(1)} percentage points, assuming equal-count unrelated cards leave the Main Deck.</p>}{scenarios.length > 1 && <button type="button" onClick={() => { const remaining = scenarios.filter((scenario) => scenario.id !== active.id); setScenarios(remaining); setActiveId(remaining[0].id); }} className="text-xs text-ctp-red">Remove scenario</button>}</div>; })()}</div></div>}
    <div className="mt-4 overflow-x-auto"><table className="w-full min-w-[38rem] text-left text-xs"><thead className="text-ctp-subtext0"><tr><th className="px-2 py-2">Opposing plan</th><th className="px-2 py-2 text-right">Deadline</th><th className="px-2 py-2 text-right">Main answers</th><th className="px-2 py-2 text-right">Preboard</th><th className="px-2 py-2 text-right">Postboard</th><th className="px-2 py-2 text-right">Gain</th></tr></thead><tbody>{rows.map(({ scenario, result }) => <tr key={scenario.id} className="border-t border-ctp-surface1"><td className="px-2 py-2 font-medium text-ctp-text">{scenario.name || "Untitled scenario"}</td><td className="px-2 py-2 text-right">T{scenario.turn}</td><td className="px-2 py-2 text-right tabular-nums">{result.mainCopies}</td><td className="px-2 py-2 text-right tabular-nums">{percent(result.preboardProbability)}</td><td className="px-2 py-2 text-right tabular-nums text-ctp-blue">{percent(result.postboardProbability)}</td><td className="px-2 py-2 text-right tabular-nums text-ctp-green">+{(result.gain * 100).toFixed(1)}</td></tr>)}</tbody></table></div>
    <p className="mt-3 text-[11px] leading-4 text-ctp-subtext0">Exact chance of seeing at least one selected answer by each deadline. Postboard assumes every selected Sideboard copy enters and an unrelated card leaves, preserving Main Deck size. It does not verify that a chosen card answers the named plan or predict matchup win rate.</p>
  </section>;
}

function Metric({ label, value }: { label: string; value: string }) { return <div className="rounded-lg border border-ctp-surface1 bg-ctp-base/40 p-3"><p className="text-[9px] uppercase tracking-wide text-ctp-subtext0">{label}</p><p className="mt-1 text-lg font-bold tabular-nums text-ctp-text">{value}</p></div>; }
