import { useMemo, useState } from "react";
import type { Card } from "@gatcg/shared";
import { computeLevelGoalAnalysis } from "../../lib/levelGoal";
import { computeLevelRunway } from "../../lib/levelRunway";
import { inferStartingHandSize, naturalCardsSeenByTurn, naturalLevelByTurn, type PlayOrder } from "../../lib/turnToPlay";

interface Line { name: string; quantity: number }
const percent = (value: number | null) => value == null ? "—" : `${(value * 100).toFixed(1)}%`;

export default function LevelUpRunway({ mainLines, materialLines, catalogByName }: { mainLines: Line[]; materialLines: Line[]; catalogByName: Map<string, Card> }) {
  const [targetLevel, setTargetLevel] = useState(3);
  const [targetTurn, setTargetTurn] = useState(3);
  const [playOrder, setPlayOrder] = useState<PlayOrder>("first");
  const [followUpReserve, setFollowUpReserve] = useState(3);
  const startingHand = inferStartingHandSize(materialLines, catalogByName);
  const analyses = useMemo(() => Array.from({ length: 8 }, (_, index) => computeLevelGoalAnalysis(mainLines, materialLines, catalogByName, { targetLevel, targetTurn: index + 1, playOrder, useDirectLevelUp: true, useFractalPayment: true, fragmentedSpiritDepth: 12 })), [mainLines, materialLines, catalogByName, targetLevel, playOrder]);
  const selected = analyses[targetTurn - 1];
  const runway = computeLevelRunway(startingHand, playOrder, targetTurn, followUpReserve);
  const strongest = selected.routes.filter((route) => route.id !== "fractal" && route.probability != null).sort((a, b) => (b.probability ?? 0) - (a.probability ?? 0))[0] ?? null;
  const direct = selected.routes.find((route) => route.id === "direct");
  const fractal = selected.routes.find((route) => route.id === "fractal");
  const levelCards = materialLines.filter((line) => catalogByName.get(line.name)?.types.includes("CHAMPION")).sort((a, b) => (catalogByName.get(a.name)?.level ?? 0) - (catalogByName.get(b.name)?.level ?? 0));

  return <section data-component="LevelUpRunway" className="pt-3">
    <div><h3 className="font-semibold text-ctp-text">Level-Up Runway</h3><p className="mt-1 max-w-2xl text-xs text-ctp-subtext0">See when the lineage reaches a chosen level, whether detected acceleration can beat the normal schedule, and when a follow-up Reserve play fits the natural hand ceiling.</p></div>
    <div className="mt-4 grid gap-3 sm:grid-cols-4"><Control label="Target level" value={targetLevel} onChange={setTargetLevel} values={[2,3,4,5,6]} prefix="Level " /><Control label="Target turn" value={targetTurn} onChange={setTargetTurn} values={[1,2,3,4,5,6,7,8]} prefix="Turn " /><label className="text-xs text-ctp-subtext0">Play order<select value={playOrder} onChange={(event) => setPlayOrder(event.target.value as PlayOrder)} className="mt-1 block w-full rounded-md border border-ctp-surface1 bg-ctp-base px-2 py-2 text-sm text-ctp-text"><option value="first">Going first</option><option value="second">Going second</option></select></label><Control label="Follow-up Reserve" value={followUpReserve} onChange={setFollowUpReserve} values={[0,1,2,3,4,5,6,7,8,9,10]} prefix="Reserve " /></div>
    <div className="mt-4 grid gap-2 sm:grid-cols-4"><Metric label="Normal schedule" value={`Turn ${selected.naturalTurn}`} /><Metric label={`Best route by T${targetTurn}`} value={strongest ? percent(strongest.probability) : "—"} /><Metric label="Direct acceleration" value={percent(direct?.probability ?? null)} /><Metric label="Follow-up fits" value={runway.recoveryTurn == null ? "After T8" : `Turn ${runway.recoveryTurn}`} /></div>
    <div className="mt-4 overflow-x-auto"><table className="w-full min-w-[42rem] text-xs"><thead className="text-ctp-subtext0"><tr><th className="px-2 py-1.5 text-left">Turn</th>{analyses.map((_, index) => <th key={index} className="px-2 py-1.5 text-right">{index + 1}</th>)}</tr></thead><tbody><tr className="border-t border-ctp-surface1"><th className="px-2 py-2 text-left font-medium text-ctp-text">Natural level</th>{analyses.map((_, index) => <td key={index} className="px-2 py-2 text-right tabular-nums">{naturalLevelByTurn(index + 1)}</td>)}</tr><tr className="border-t border-ctp-surface0"><th className="px-2 py-2 text-left font-medium text-ctp-text">Reach level {targetLevel}</th>{analyses.map((analysis, index) => { const best = analysis.routes.filter((route) => route.id !== "fractal" && route.probability != null).reduce<number>((value, route) => Math.max(value, route.probability ?? 0), 0); return <td key={index} className="px-2 py-2 text-right font-medium tabular-nums text-ctp-mauve">{percent(best)}</td>; })}</tr><tr className="border-t border-ctp-surface0"><th className="px-2 py-2 text-left font-medium text-ctp-text">Cards seen</th>{analyses.map((_, index) => <td key={index} className="px-2 py-2 text-right tabular-nums text-ctp-subtext1">{naturalCardsSeenByTurn(index + 1, startingHand, playOrder)}</td>)}</tr><tr className="border-t border-ctp-surface0"><th className="px-2 py-2 text-left font-medium text-ctp-text">Follow-up margin</th>{runway.points.map((point) => <td key={point.turn} className={`px-2 py-2 text-right font-medium tabular-nums ${point.margin >= 0 ? "text-ctp-green" : "text-ctp-red"}`}>{point.margin >= 0 ? `+${point.margin}` : point.margin}</td>)}</tr></tbody></table></div>
    <div className="mt-4 grid gap-3 lg:grid-cols-2"><div className="rounded-lg border border-ctp-surface1 bg-ctp-base/35 p-3"><h4 className="text-xs font-semibold text-ctp-text">Detected lineage</h4>{levelCards.length ? <ul className="mt-2 space-y-1 text-xs text-ctp-subtext1">{levelCards.map((line) => <li key={line.name}>L{catalogByName.get(line.name)?.level ?? "?"} · {line.name}</li>)}</ul> : <p className="mt-2 text-xs text-ctp-yellow">No Champion lineage was detected in Material.</p>}</div><div className="rounded-lg border border-ctp-surface1 bg-ctp-base/35 p-3"><h4 className="text-xs font-semibold text-ctp-text">What affects the route</h4><p className="mt-2 text-xs text-ctp-subtext1">{strongest?.detail ?? "No supported route is available."}</p>{strongest?.bottleneck && <p className="mt-2 text-xs text-ctp-yellow">{strongest.bottleneck}</p>}{fractal?.probability != null && <p className="mt-2 text-xs text-ctp-subtext0">Fractal payment access: {percent(fractal.probability)}. It supports payment but cannot create an earlier Materialize Phase.</p>}</div></div>
    <p className="mt-3 text-[11px] leading-4 text-ctp-subtext0">The level route follows the supported rules model. Follow-up margin is only a natural hand-size ceiling: Reserve cost plus the played card, with no earlier spending subtracted. It is not a promise that resources survive the level-up turn.</p>
  </section>;
}

function Control({ label, value, onChange, values, prefix }: { label: string; value: number; onChange: (value: number) => void; values: number[]; prefix: string }) { return <label className="text-xs text-ctp-subtext0">{label}<select value={value} onChange={(event) => onChange(Number(event.target.value))} className="mt-1 block w-full rounded-md border border-ctp-surface1 bg-ctp-base px-2 py-2 text-sm text-ctp-text">{values.map((item) => <option key={item} value={item}>{prefix}{item}</option>)}</select></label>; }
function Metric({ label, value }: { label: string; value: string }) { return <div className="rounded-lg border border-ctp-surface1 bg-ctp-base/40 p-3"><p className="text-[9px] uppercase tracking-wide text-ctp-subtext0">{label}</p><p className="mt-1 text-lg font-bold tabular-nums text-ctp-text">{value}</p></div>; }
