import { useEffect, useMemo, useState } from "react";
import { playtestDeckFingerprint, summarizePlaytests, type PlaytestOrder, type PlaytestRecord, type PlaytestResult } from "../../lib/playtestTracker";

interface Line { name: string; quantity: number }
const STORAGE_PREFIX = "deck-playtests-v1:";
const percent = (value: number | null) => value == null ? "—" : `${(value * 100).toFixed(0)}%`;

function load(key: string): PlaytestRecord[] {
  try { const value = JSON.parse(localStorage.getItem(key) ?? "[]") as PlaytestRecord[]; return Array.isArray(value) ? value.filter((record) => record && typeof record.id === "string") : []; } catch { return []; }
}

export default function PlaytestSessionTracker({ title, championName, mainLines }: { title: string | null; championName: string | null; mainLines: Line[] }) {
  const fingerprint = useMemo(() => playtestDeckFingerprint(championName, mainLines), [championName, mainLines]);
  const storageKey = `${STORAGE_PREFIX}${fingerprint}`;
  const [records, setRecords] = useState<PlaytestRecord[]>(() => load(storageKey));
  const [opponent, setOpponent] = useState("");
  const [result, setResult] = useState<PlaytestResult>("win");
  const [order, setOrder] = useState<PlaytestOrder>("first");
  const [onlineTurn, setOnlineTurn] = useState("");
  const [reached, setReached] = useState(false);
  const [bottleneck, setBottleneck] = useState("");
  const [notes, setNotes] = useState("");
  useEffect(() => { try { localStorage.setItem(storageKey, JSON.stringify(records)); } catch { /* Local storage may be unavailable. */ } }, [records, storageKey]);
  const summary = summarizePlaytests(records);
  function addRecord() {
    const parsedTurn = onlineTurn ? Math.max(1, Math.min(30, Math.floor(Number(onlineTurn)))) : null;
    setRecords((current) => [{ id: crypto.randomUUID(), playedAt: new Date().toISOString(), opponent: opponent.trim(), result, order, onlineTurn: parsedTurn, reachedWinCondition: reached, bottleneck: bottleneck.trim(), notes: notes.trim() }, ...current]);
    setOpponent(""); setOnlineTurn(""); setReached(false); setBottleneck(""); setNotes("");
  }

  return <section data-component="PlaytestSessionTracker" className="pt-3">
    <div><h3 className="font-semibold text-ctp-text">Test Session Tracker</h3><p className="mt-1 max-w-2xl text-xs text-ctp-subtext0">Record actual games for this exact deck configuration. Records stay in this browser and reset to a separate history when the Main Deck changes.</p></div>
    <div className="mt-4 grid gap-2 sm:grid-cols-3 lg:grid-cols-6"><Metric label="Games" value={`${summary.games}`} /><Metric label="Observed win rate" value={percent(summary.winRate)} /><Metric label="Going first" value={percent(summary.firstWinRate)} /><Metric label="Going second" value={percent(summary.secondWinRate)} /><Metric label="Avg. online" value={summary.averageOnlineTurn == null ? "—" : `T${summary.averageOnlineTurn.toFixed(1)}`} /><Metric label="Win-con reached" value={percent(summary.winConditionRate)} /></div>
    <div className="mt-4 grid gap-4 lg:grid-cols-[minmax(0,0.9fr)_minmax(0,1.1fr)]"><div className="rounded-xl border border-ctp-surface1 bg-ctp-base/35 p-3"><h4 className="text-sm font-semibold text-ctp-text">Log a game</h4><div className="mt-3 grid gap-2 sm:grid-cols-2"><label className="text-xs text-ctp-subtext0 sm:col-span-2">Opponent or archetype<input value={opponent} onChange={(event) => setOpponent(event.target.value)} placeholder="Optional" className="mt-1 block w-full rounded-md border border-ctp-surface1 bg-ctp-mantle px-3 py-2 text-sm text-ctp-text" /></label><Select label="Result" value={result} onChange={(value) => setResult(value as PlaytestResult)} options={[['win','Win'],['loss','Loss'],['draw','Draw']]} /><Select label="Play order" value={order} onChange={(value) => setOrder(value as PlaytestOrder)} options={[['first','Going first'],['second','Going second']]} /><label className="text-xs text-ctp-subtext0">Plan online turn<input type="number" min={1} max={30} value={onlineTurn} onChange={(event) => setOnlineTurn(event.target.value)} placeholder="Optional" className="mt-1 block w-full rounded-md border border-ctp-surface1 bg-ctp-mantle px-3 py-2 text-sm text-ctp-text" /></label><label className="flex items-end gap-2 pb-2 text-xs text-ctp-subtext1"><input type="checkbox" checked={reached} onChange={(event) => setReached(event.target.checked)} /> Reached win condition</label><label className="text-xs text-ctp-subtext0 sm:col-span-2">Primary bottleneck<input value={bottleneck} onChange={(event) => setBottleneck(event.target.value)} placeholder="Setup, interaction, resources…" className="mt-1 block w-full rounded-md border border-ctp-surface1 bg-ctp-mantle px-3 py-2 text-sm text-ctp-text" /></label><label className="text-xs text-ctp-subtext0 sm:col-span-2">Notes<textarea value={notes} onChange={(event) => setNotes(event.target.value)} rows={2} className="mt-1 block w-full rounded-md border border-ctp-surface1 bg-ctp-mantle px-3 py-2 text-sm text-ctp-text" /></label></div><button type="button" onClick={addRecord} className="mt-3 rounded-md bg-ctp-blue px-4 py-2 text-sm font-semibold text-ctp-base">Add game</button></div>
      <div><div className="flex items-center justify-between gap-2"><h4 className="text-sm font-semibold text-ctp-text">{title ?? championName ?? "This deck"} · recent games</h4><span className="text-[10px] text-ctp-subtext0">Deck {fingerprint}</span></div>{records.length === 0 ? <p className="mt-3 rounded-lg border border-dashed border-ctp-surface1 p-5 text-center text-xs text-ctp-subtext0">No games recorded for this version yet.</p> : <div className="mt-2 max-h-96 space-y-2 overflow-y-auto">{records.map((record) => <article key={record.id} className="rounded-lg border border-ctp-surface1 bg-ctp-base/35 p-3"><div className="flex items-start justify-between gap-3"><div><p className="text-sm font-medium text-ctp-text">{record.opponent || "Unspecified opponent"}</p><p className="mt-0.5 text-[10px] text-ctp-subtext0">{new Date(record.playedAt).toLocaleDateString()} · {record.order === "first" ? "First" : "Second"}{record.onlineTurn ? ` · Online T${record.onlineTurn}` : ""}</p></div><span className={`rounded-full px-2 py-0.5 text-[10px] font-bold uppercase ${record.result === "win" ? "bg-ctp-green/10 text-ctp-green" : record.result === "loss" ? "bg-ctp-red/10 text-ctp-red" : "bg-ctp-yellow/10 text-ctp-yellow"}`}>{record.result}</span></div>{record.bottleneck && <p className="mt-2 text-xs text-ctp-yellow">Bottleneck: {record.bottleneck}</p>}{record.notes && <p className="mt-1 text-xs text-ctp-subtext1">{record.notes}</p>}<button type="button" onClick={() => setRecords((current) => current.filter((item) => item.id !== record.id))} className="mt-2 text-[10px] text-ctp-red">Remove</button></article>)}</div>}{summary.topBottlenecks.length > 0 && <div className="mt-3 rounded-lg border border-ctp-surface1 p-3"><p className="text-[10px] font-semibold uppercase tracking-wide text-ctp-subtext0">Recurring bottlenecks</p><div className="mt-2 flex flex-wrap gap-1.5">{summary.topBottlenecks.map((item) => <span key={item.label} className="rounded-full bg-ctp-yellow/10 px-2 py-1 text-xs text-ctp-yellow">{item.label} · {item.games}</span>)}</div></div>}{summary.conversionRate != null && <p className="mt-3 text-xs text-ctp-subtext1">When the win condition was reached, observed match points were <b className="text-ctp-text">{percent(summary.conversionRate)}</b>.</p>}</div></div>
    <p className="mt-3 text-[11px] leading-4 text-ctp-subtext0">These are self-recorded observations, not tournament telemetry. Small samples, opponent selection, repeated testing partners, deck familiarity, and record-keeping choices can strongly bias the results.</p>
  </section>;
}

function Select({ label, value, onChange, options }: { label: string; value: string; onChange: (value: string) => void; options: [string,string][] }) { return <label className="text-xs text-ctp-subtext0">{label}<select value={value} onChange={(event) => onChange(event.target.value)} className="mt-1 block w-full rounded-md border border-ctp-surface1 bg-ctp-mantle px-3 py-2 text-sm text-ctp-text">{options.map(([key, text]) => <option key={key} value={key}>{text}</option>)}</select></label>; }
function Metric({ label, value }: { label: string; value: string }) { return <div className="rounded-lg border border-ctp-surface1 bg-ctp-base/40 p-2"><p className="text-[9px] uppercase tracking-wide text-ctp-subtext0">{label}</p><p className="mt-1 text-lg font-bold tabular-nums text-ctp-text">{value}</p></div>; }
