import { useMemo, useState } from "react";
import type { Card } from "@gatcg/shared";
import { Link } from "react-router-dom";
import CardImage from "../../components/CardImage";
import Panel from "../../components/ui/Panel";
import Section from "../../components/ui/Section";
import { inferStartingHandSize } from "../../lib/turnToPlay";
import { computeReserveSequence, type ReserveSequenceStep } from "./reserveSequence";

const inputClass = "min-h-9 rounded-md border border-ctp-surface1 bg-ctp-mantle px-2 py-1 text-xs text-ctp-text";
const percent = (value: number) => `${(value * 100).toFixed(1)}%`;

export default function ReserveSequencePressure({ mainLines, materialLines, catalogByName }: { mainLines: { name: string; quantity: number }[]; materialLines: { name: string; quantity: number }[]; catalogByName: Map<string, Card>; }) {
  const options = useMemo(() => mainLines.filter((line) => catalogByName.get(line.name)?.cost.type === "reserve"), [mainLines, catalogByName]);
  const [steps, setSteps] = useState<ReserveSequenceStep[]>([]);
  const startingHandSize = useMemo(() => inferStartingHandSize(materialLines, catalogByName), [materialLines, catalogByName]);
  const result = useMemo(() => computeReserveSequence(mainLines, catalogByName, steps, startingHandSize), [mainLines, catalogByName, steps, startingHandSize]);
  const delayed = useMemo(() => computeReserveSequence(mainLines, catalogByName, steps.map((step) => ({ ...step, turn: step.turn + 1 })), startingHandSize), [mainLines, catalogByName, steps, startingHandSize]);
  const conditionalDiscounts = steps.filter((step) => /\bcosts?\s+(?:\d+|x|lv)\s+less\s+to\s+activate\b/i.test((catalogByName.get(step.name)?.effect ?? "").replace(/\*\*/g, "")));
  if (options.length === 0) return null;

  function addStep(name: string) {
    if (!name || steps.length >= 4) return;
    const cost = Math.max(0, catalogByName.get(name)?.cost_reserve ?? 0);
    const turn = Math.max(1, steps.length + 1, cost - startingHandSize + 1);
    setSteps((current) => [...current, { name, turn, effectiveReserveCost: cost }]);
  }

  return <Panel data-component="ReserveSequencePressure" className="mt-4 shadow-sm"><Section heading="dense" title="Curve affordability check" description="Can you draw and afford up to four named plays by their deadlines?"><div className="mt-3 rounded-xl border border-ctp-mauve/30 bg-ctp-mauve/5 p-3"><p className="text-xs font-medium text-ctp-text">This is a quick curve check, not a combo simulation.</p><p className="mt-1 text-[11px] leading-4 text-ctp-subtext1">Use Combo Lab when pieces are interchangeable, a line has branching requirements, or you want to save and share a combo.</p><Link to="/combo-lab" className="mt-2 inline-flex min-h-11 items-center rounded-lg px-1 text-xs font-semibold text-ctp-mauve hover:underline">Open this deck in Combo Lab →</Link></div><div className="mt-3 flex flex-wrap items-end gap-2"><label className="text-[10px] uppercase tracking-wide text-ctp-subtext0">Add a play<select defaultValue="" onChange={(event) => { addStep(event.target.value); event.target.value = ""; }} className={`mt-1 block max-w-72 ${inputClass}`}><option value="">Choose a card…</option>{options.map((line) => <option key={line.name} value={line.name}>{line.name} · R{catalogByName.get(line.name)?.cost_reserve ?? 0} · {line.quantity}×</option>)}</select></label><span className="pb-2 text-[10px] text-ctp-subtext0">Up to four cards; repeat a name to require another copy.</span></div>
  {steps.length === 0 ? <p className="mt-3 rounded-lg border border-dashed border-ctp-surface1 p-4 text-center text-xs text-ctp-subtext0">Add cards in the order you want to play them.</p> : <><div className="mt-3 space-y-2">{steps.map((step, index) => { const card = catalogByName.get(step.name); const hasDiscount = /\bcosts?\s+(?:\d+|x|lv)\s+less\s+to\s+activate\b/i.test((card?.effect ?? "").replace(/\*\*/g, "")); return <div key={`${step.name}-${index}`} className="grid grid-cols-[3.5rem_1fr] items-end gap-3 rounded-xl border border-ctp-surface1 bg-ctp-base/35 p-3 sm:grid-cols-[3.5rem_minmax(0,1fr)_5rem_7rem_auto]"><Link to={card ? `/cards/${card.slug}` : "#"} aria-label={`View ${step.name}`} className="row-span-2 self-start sm:row-span-1"><div className="aspect-[5/7] overflow-hidden rounded-lg bg-ctp-surface0">{card?.editions[0] ? <CardImage image={card.editions[0].image} alt={step.name} className="h-full w-full object-cover" /> : <span className="flex h-full items-center justify-center p-1 text-center text-[8px] text-ctp-subtext0">{step.name}</span>}</div></Link><div className="min-w-0 self-center"><div className="truncate text-sm font-medium text-ctp-text">{index + 1}. {step.name}</div><div className="text-[10px] text-ctp-subtext0">Printed Reserve {card?.cost_reserve ?? 0}{hasDiscount ? " · discount detected" : ""}</div></div><div className="col-span-2 grid grid-cols-2 gap-2 sm:col-span-1 sm:contents"><label className="text-[10px] text-ctp-subtext0">Turn<input type="number" min={1} max={20} value={step.turn} onChange={(event) => setSteps((current) => current.map((item, itemIndex) => itemIndex === index ? { ...item, turn: Math.max(1, Math.min(20, Math.round(Number(event.target.value) || 1))) } : item))} className={`mt-1 w-full ${inputClass}`} /></label><label className="text-[10px] text-ctp-subtext0">Effective cost<input type="number" min={0} max={99} value={step.effectiveReserveCost ?? card?.cost_reserve ?? 0} onChange={(event) => setSteps((current) => current.map((item, itemIndex) => itemIndex === index ? { ...item, effectiveReserveCost: Math.max(0, Math.min(99, Math.round(Number(event.target.value) || 0))) } : item))} className={`mt-1 w-full ${inputClass}`} /></label></div><button type="button" onClick={() => setSteps((current) => current.filter((_, itemIndex) => itemIndex !== index))} className="col-span-2 min-h-11 rounded-lg px-3 text-xs text-ctp-subtext0 hover:bg-ctp-red/10 hover:text-ctp-red sm:col-span-1">Remove</button></div>; })}</div>
  <div className="mt-3 grid gap-2 sm:grid-cols-3"><Metric label="Drawn by deadlines" value={percent(result.probability)} /><Metric label="Sequence playable" value={percent(result.playableProbability)} tone={result.feasible ? "good" : "warn"} /><Metric label="Delay every play 1 turn" value={percent(delayed.playableProbability)} detail={`${((delayed.playableProbability - result.playableProbability) * 100).toFixed(1)} pt change`} tone="good" /></div>
  <div className="mt-3 space-y-2 sm:hidden">{result.pressure.map((point) => <div key={point.turn} className="rounded-lg border border-ctp-surface1 bg-ctp-base/35 p-3"><div className="flex items-start justify-between gap-3"><div><p className="text-xs font-semibold text-ctp-text">T{point.turn} · {point.cards.join(" + ")}</p><p className="mt-1 text-[10px] text-ctp-subtext0">{point.reserveCost} Reserve · {point.cardsNeeded} cards needed</p></div><span className={`shrink-0 text-xs font-semibold ${point.margin >= 0 ? "text-ctp-green" : "text-ctp-red"}`}>{point.margin >= 0 ? `${point.margin} spare` : `${Math.abs(point.margin)} short`}</span></div></div>)}</div>
  <div className="mt-3 hidden overflow-x-auto sm:block"><table className="w-full min-w-[34rem] text-left text-xs"><thead className="text-[10px] uppercase tracking-wide text-ctp-subtext0"><tr><th className="pb-2">Turn</th><th className="pb-2">Plays</th><th className="pb-2">Reserve</th><th className="pb-2">Hand ceiling</th><th className="pb-2">Cards needed</th><th className="pb-2">Pressure</th></tr></thead><tbody>{result.pressure.map((point) => <tr key={point.turn} className="border-t border-ctp-surface1"><td className="py-2 font-semibold text-ctp-text">T{point.turn}</td><td className="max-w-64 py-2 text-ctp-subtext1">{point.cards.join(" + ")}</td><td className="py-2 tabular-nums text-ctp-subtext1">{point.reserveCost}</td><td className="py-2 tabular-nums text-ctp-subtext1">{point.handCeiling}</td><td className="py-2 tabular-nums text-ctp-subtext1">{point.cardsNeeded}</td><td className={`py-2 font-medium ${point.margin >= 0 ? "text-ctp-green" : "text-ctp-red"}`}>{point.margin >= 0 ? `${point.margin} spare` : `${Math.abs(point.margin)} short`}{point.floatingPotential > 0 ? ` · up to ${point.floatingPotential} FM` : ""}</td></tr>)}</tbody></table></div>
  {conditionalDiscounts.length > 0 && <p className="mt-2 rounded-lg border border-ctp-yellow/30 bg-ctp-yellow/5 p-2 text-[10px] text-ctp-yellow">Cost reduction detected on {[...new Set(conditionalDiscounts.map((step) => step.name))].join(", ")}. Set each effective cost above only when its printed condition is satisfied.</p>}<details className="mt-2 text-[10px] leading-4 text-ctp-subtext0"><summary className="cursor-pointer">How this is calculated</summary><p className="mt-1">Exact deadline draw odds; no mulligan. Hand ceiling starts at {startingHandSize}, adds one normal draw each turn, subtracts earlier selected plays, and assumes no other cards are spent. The entered effective cost accounts for conditional reductions for that play. Floating Memory is shown as potential relief but is not automatically applied.</p></details></>}</Section></Panel>;
}

function Metric({ label, value, detail, tone }: { label: string; value: string; detail?: string; tone?: "good" | "warn"; }) { return <div className="rounded-lg border border-ctp-surface1 bg-ctp-base/35 p-2.5"><div className="text-[10px] uppercase tracking-wide text-ctp-subtext0">{label}</div><div className={`font-semibold tabular-nums ${tone === "good" ? "text-ctp-teal" : tone === "warn" ? "text-ctp-red" : "text-ctp-text"}`}>{value}</div>{detail && <div className="text-[10px] text-ctp-subtext0">{detail}</div>}</div>; }
