import { useMemo, useState } from "react";
import type { Card } from "@gatcg/shared";
import CostBreakdown from "../../components/CostBreakdown";
import Panel from "../../components/ui/Panel";
import Section from "../../components/ui/Section";
import { inferStartingHandSize } from "../../lib/turnToPlay";
import { computeResourceCurveReliability } from "./resourceCurve";

function status(probability: number) { if (probability >= 0.8) return { label: "Reliable", className: "text-ctp-green" }; if (probability >= 0.6) return { label: "Playable", className: "text-ctp-blue" }; return { label: "Thin", className: "text-ctp-yellow" }; }

export default function ResourceCurveReliability({ mainLines, materialLines, catalogByName, sharedEffectiveCosts, onSharedEffectiveCostsChange }: { mainLines: { name: string; quantity: number }[]; materialLines: { name: string; quantity: number }[]; catalogByName: Map<string, Card>; sharedEffectiveCosts?: Record<string, number>; onSharedEffectiveCostsChange?: (costs: Record<string, number>) => void }) {
  const [localEffectiveCosts, setLocalEffectiveCosts] = useState<Record<string, number>>({});
  const effectiveCosts = sharedEffectiveCosts ?? localEffectiveCosts;
  const setEffectiveCosts = (updater: (current: Record<string, number>) => Record<string, number>) => onSharedEffectiveCostsChange ? onSharedEffectiveCostsChange(updater(effectiveCosts)) : setLocalEffectiveCosts(updater);
  const opening = useMemo(() => inferStartingHandSize(materialLines, catalogByName), [materialLines, catalogByName]);
  const points = useMemo(() => computeResourceCurveReliability(mainLines, catalogByName, opening, effectiveCosts), [mainLines, catalogByName, opening, effectiveCosts]);
  const discounted = mainLines.filter((line) => /\bcosts?\b[^.\n]{0,90}\bless\s+to\s+activate\b/i.test((catalogByName.get(line.name)?.effect ?? "").replace(/\*\*/g, "")));
  if (points.length === 0) return null;
  return <Panel data-component="ResourceCurveReliability" className="mt-4 shadow-sm"><Section heading="dense" title="Resource timing" description="When each effective Reserve-cost band first becomes affordable, and how likely the deck is to have drawn one.">
    {discounted.length > 0 && <details className="mt-3 rounded-xl border border-ctp-yellow/30 bg-ctp-yellow/5 p-3"><summary className="flex min-h-11 cursor-pointer items-center text-xs font-semibold text-ctp-yellow">Set cost assumptions before calculating ({discounted.length})</summary><div className="mt-2 space-y-3">{discounted.map((line) => { const card = catalogByName.get(line.name); const printed = card?.cost_reserve ?? 0; return <div key={line.name} className="rounded-lg border border-ctp-surface1 p-2"><label className="grid grid-cols-[minmax(0,1fr)_5rem] items-center gap-3 text-xs text-ctp-subtext1"><span>{line.name} <span className="text-ctp-subtext0">(printed {printed})</span></span><input aria-label={`Effective Reserve cost for ${line.name}`} type="number" min={0} max={99} value={effectiveCosts[line.name] ?? printed} onChange={(event) => setEffectiveCosts((current) => ({ ...current, [line.name]: Math.max(0, Math.round(Number(event.target.value) || 0)) }))} className="min-h-11 rounded-lg border border-ctp-surface1 bg-ctp-base px-2 text-sm text-ctp-text" /></label>{card && <CostBreakdown card={card} effectiveCost={effectiveCosts[line.name]} compact />}</div>; })}</div><p className="mt-2 text-[10px] leading-4 text-ctp-subtext0">Choose a reduced value only when you expect the disclosed condition to be satisfied. Variable, board-state, target, and limited-use reductions are never assumed automatically.</p></details>}
    <div className="mt-3 space-y-3">{points.map((point) => { const read = status(point.first.probability); return <article key={point.cost} className="rounded-xl border border-ctp-surface1 bg-ctp-base/35 p-3"><div className="flex items-start justify-between gap-3"><div><p className="text-sm font-semibold text-ctp-text">Reserve {point.cost}</p><p className="text-[10px] text-ctp-subtext0">{point.copies} copies · first affordable T{point.first.turn}{point.second.turn < point.first.turn ? ` / T${point.second.turn} going second` : ""}</p></div><div className="text-right"><p className={`text-lg font-bold tabular-nums ${read.className}`}>{(point.first.probability * 100).toFixed(1)}%</p><p className={`text-[10px] font-medium ${read.className}`}>{read.label} going first</p></div></div><div className="mt-3 space-y-2"><ReliabilityBar label={`First · T${point.first.turn}`} probability={point.first.probability} /><ReliabilityBar label={`Second · T${point.second.turn}`} probability={point.second.probability} /></div><div className="mt-3 flex gap-2 overflow-x-auto">{mainLines.filter((line) => (effectiveCosts[line.name] ?? catalogByName.get(line.name)?.cost_reserve) === point.cost).map((line) => { const card = catalogByName.get(line.name); return <div key={line.name} className="w-24 shrink-0"><p className="truncate text-[10px] font-medium text-ctp-text">{line.name}</p>{card && <CostBreakdown card={card} effectiveCost={effectiveCosts[line.name]} compact />}</div>; })}</div></article>; })}</div>
    <details className="mt-3 text-[10px] leading-4 text-ctp-subtext0"><summary className="flex min-h-11 cursor-pointer items-center">How this is calculated</summary><p className="mt-1">Exact draw odds use the level-0 Champion's starting hand. Conditional cards use the selected effective costs; others use printed Reserve cost. The model does not prove a condition occurred, spend prior resources, or apply unsupported variable reductions.</p></details>
  </Section></Panel>;
}

function ReliabilityBar({ label, probability }: { label: string; probability: number }) { const read = status(probability); return <div className="grid grid-cols-[5.5rem_1fr_3rem] items-center gap-2 text-[10px]"><span className="text-ctp-subtext0">{label}</span><span className="h-2.5 overflow-hidden rounded-full bg-ctp-surface0"><span className="block h-full rounded-full bg-ctp-blue" style={{ width: `${probability * 100}%` }} /></span><span className={`text-right font-semibold tabular-nums ${read.className}`}>{(probability * 100).toFixed(1)}%</span></div>; }
