import { useMemo, useState } from "react";
import type { Card } from "@gatcg/shared";
import { computeStageDrawQuality } from "../../lib/stageDrawQuality";
import { inferStartingHandSize, type PlayOrder } from "../../lib/turnToPlay";

interface Line { name: string; quantity: number }
type Role = "early" | "late" | "flexible" | "conditional";
const LABEL: Record<Role, string> = { early: "Early-only", late: "Late-only", flexible: "Flexible", conditional: "Conditional" };
const percent = (value: number) => `${(value * 100).toFixed(1)}%`;

export default function StageDrawQuality({ mainLines, materialLines, catalogByName }: { mainLines: Line[]; materialLines: Line[]; catalogByName: Map<string, Card> }) {
  const [assignments, setAssignments] = useState<Record<string, Role | "">>({});
  const [earlyTurn, setEarlyTurn] = useState(2);
  const [lateTurn, setLateTurn] = useState(6);
  const [maximumClunk, setMaximumClunk] = useState(1);
  const [playOrder, setPlayOrder] = useState<PlayOrder>("first");
  const [query, setQuery] = useState("");
  const pools = useMemo(() => ({ early: mainLines.filter((line) => assignments[line.name] === "early"), late: mainLines.filter((line) => assignments[line.name] === "late"), flexible: mainLines.filter((line) => assignments[line.name] === "flexible"), conditional: mainLines.filter((line) => assignments[line.name] === "conditional") }), [assignments, mainLines]);
  const copies = (role: Role) => pools[role].reduce((sum, line) => sum + line.quantity, 0);
  const deckSize = mainLines.reduce((sum, line) => sum + line.quantity, 0);
  const result = computeStageDrawQuality(deckSize, inferStartingHandSize(materialLines, catalogByName), { earlyCopies: copies("early"), lateCopies: copies("late"), flexibleCopies: copies("flexible"), conditionalCopies: copies("conditional") }, earlyTurn, lateTurn, playOrder, maximumClunk);
  const filtered = mainLines.filter((line) => line.name.toLowerCase().includes(query.trim().toLowerCase()));
  const ready = copies("early") + copies("flexible") > 0 && copies("late") + copies("flexible") > 0;

  return <section data-component="StageDrawQuality" className="pt-3">
    <div><h3 className="font-semibold text-ctp-text">Draw Quality by Game Stage</h3><p className="mt-1 max-w-2xl text-xs text-ctp-subtext0">Classify cards by when they are useful, then measure an early functional draw pattern followed by fresh late impact.</p></div>
    <div className="mt-4 grid gap-3 lg:grid-cols-[minmax(0,1.2fr)_minmax(18rem,0.8fr)]"><div><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Filter cards…" aria-label="Filter draw quality cards" className="w-full rounded-md border border-ctp-surface1 bg-ctp-base px-3 py-2 text-sm text-ctp-text" /><div className="mt-2 max-h-80 overflow-y-auto rounded-lg border border-ctp-surface1">{filtered.map((line) => <div key={line.name} className="grid grid-cols-[minmax(0,1fr)_8.5rem] items-center gap-2 border-b border-ctp-surface0 px-3 py-2 last:border-0"><div className="min-w-0"><p className="truncate text-sm text-ctp-text">{line.name}</p><p className="text-[10px] text-ctp-subtext0">{line.quantity} copies</p></div><select value={assignments[line.name] ?? ""} onChange={(event) => setAssignments((current) => ({ ...current, [line.name]: event.target.value as Role | "" }))} aria-label={`Game-stage role for ${line.name}`} className="rounded-md border border-ctp-surface1 bg-ctp-mantle px-2 py-1.5 text-xs text-ctp-text"><option value="">Unassigned</option><option value="early">Early-only</option><option value="late">Late-only</option><option value="flexible">Flexible</option><option value="conditional">Conditional</option></select></div>)}</div></div>
      <div className="space-y-3"><div className="grid grid-cols-2 gap-2">{(Object.keys(pools) as Role[]).map((role) => <div key={role} className="rounded-lg border border-ctp-surface1 bg-ctp-base/40 p-2"><p className="text-xs font-semibold text-ctp-text">{LABEL[role]}</p><p className="mt-1 text-xl font-bold tabular-nums text-ctp-text">{copies(role)}</p></div>)}</div><div className="grid grid-cols-2 gap-2 sm:grid-cols-4"><Turn label="Early check" value={earlyTurn} onChange={(value) => { setEarlyTurn(value); setLateTurn((current) => Math.max(current, value)); }} /><Turn label="Late check" value={lateTurn} onChange={(value) => setLateTurn(Math.max(earlyTurn, value))} /><label className="text-xs text-ctp-subtext0">Max early clunk<select value={maximumClunk} onChange={(event) => setMaximumClunk(Number(event.target.value))} className="mt-1 block w-full rounded-md border border-ctp-surface1 bg-ctp-base px-2 py-2 text-sm text-ctp-text">{[0,1,2,3,4].map((value) => <option key={value}>{value}</option>)}</select></label><label className="text-xs text-ctp-subtext0">Order<select value={playOrder} onChange={(event) => setPlayOrder(event.target.value as PlayOrder)} className="mt-1 block w-full rounded-md border border-ctp-surface1 bg-ctp-base px-2 py-2 text-sm text-ctp-text"><option value="first">First</option><option value="second">Second</option></select></label></div>{!ready ? <div className="rounded-lg border border-ctp-blue/30 bg-ctp-blue/5 p-3 text-sm text-ctp-subtext1">Assign Early/Flexible and Late/Flexible cards to evaluate both stages.</div> : <><div className="grid grid-cols-2 gap-2"><Metric label="Early functional" value={percent(result.openingFunctional)} /><Metric label="Late injection" value={percent(result.lateInjection)} /><Metric label="Both stages" value={percent(result.stagedPlan)} /><Metric label="Early clug risk" value={percent(result.earlyClog)} /></div><div className="rounded-lg border border-ctp-surface1 bg-ctp-base/35 p-3 text-xs text-ctp-subtext1"><p>Early window: {result.earlySeen} cards seen.</p><p className="mt-1">Late draw window: cards {result.earlySeen + 1}–{result.lateSeen}.</p><p className="mt-1">Chance of 2+ early-only cards by the late checkpoint: <b className="text-ctp-text">{percent(result.lateFlood)}</b>.</p></div></>}</div></div>
    <p className="mt-3 text-[11px] leading-4 text-ctp-subtext0">“Both stages” exactly requires an Early-only or Flexible card by the early checkpoint, no more than the selected Late-only/Conditional clunk cap there, and a Late-only or Flexible card drawn after that checkpoint. Categories are player judgments; costs, plays, extra draws, and game state are not modeled.</p>
  </section>;
}

function Turn({ label, value, onChange }: { label: string; value: number; onChange: (value: number) => void }) { return <label className="text-xs text-ctp-subtext0">{label}<select value={value} onChange={(event) => onChange(Number(event.target.value))} className="mt-1 block w-full rounded-md border border-ctp-surface1 bg-ctp-base px-2 py-2 text-sm text-ctp-text">{[1,2,3,4,5,6,7,8].map((turn) => <option key={turn} value={turn}>T{turn}</option>)}</select></label>; }
function Metric({ label, value }: { label: string; value: string }) { return <div className="rounded-lg border border-ctp-surface1 bg-ctp-base/40 p-2"><p className="text-[9px] uppercase tracking-wide text-ctp-subtext0">{label}</p><p className="mt-1 text-lg font-bold tabular-nums text-ctp-text">{value}</p></div>; }
